-- MPM2D part e (continued -- no delete here, part a already cleared this course's rows)

insert into public.questions
  (course_code, unit_code, subtopic_code, sort_order, difficulty,
   prompt, correct_index, options, misconception_tag)
values
('MPM2D', 'quadratics', 'factored-form-and-zeros', 9, 'Medium',
 'What is the vertex of y = (x + 3)² - 2?', 1,
 '[{"text": "(3, -2)", "feedback": "The sign of the vertex''s x-coordinate is flipped — check the sign inside the bracket carefully."}, {"text": "(-3, -2)", "feedback": "Correct. In vertex form, the vertex is (h, k); here the vertex is (-3, -2)."}, {"text": "(-3, 2)", "feedback": "The sign of the vertex''s y-coordinate is flipped — the constant at the end is the vertex''s y-coordinate exactly as written."}, {"text": "(-2, -3)", "feedback": "The x- and y-coordinates of the vertex are swapped."}]'::jsonb,
 'vertex-from-vertex-form'),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 10, 'Medium',
 'What is the vertex of y = (x - 1)² + 8?', 0,
 '[{"text": "(1, 8)", "feedback": "Correct. In vertex form, the vertex is (h, k); here the vertex is (1, 8)."}, {"text": "(-1, 8)", "feedback": "The sign of the vertex''s x-coordinate is flipped — check the sign inside the bracket carefully."}, {"text": "(1, -8)", "feedback": "The sign of the vertex''s y-coordinate is flipped — the constant at the end is the vertex''s y-coordinate exactly as written."}, {"text": "(8, 1)", "feedback": "The x- and y-coordinates of the vertex are swapped."}]'::jsonb,
 'vertex-from-vertex-form'),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 11, 'Medium',
 'What is the vertex of y = -(x + 5)² + 1?', 2,
 '[{"text": "(5, 1)", "feedback": "The sign of the vertex''s x-coordinate is flipped — check the sign inside the bracket carefully."}, {"text": "(-5, -1)", "feedback": "The sign of the vertex''s y-coordinate is flipped — the constant at the end is the vertex''s y-coordinate exactly as written."}, {"text": "(-5, 1)", "feedback": "Correct. In vertex form, the vertex is (h, k); here the vertex is (-5, 1)."}, {"text": "(1, -5)", "feedback": "The x- and y-coordinates of the vertex are swapped."}]'::jsonb,
 'vertex-from-vertex-form'),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 12, 'Medium',
 'What is the vertex of y = 2(x - 6)² - 4?', 3,
 '[{"text": "(-6, -4)", "feedback": "The sign of the vertex''s x-coordinate is flipped — check the sign inside the bracket carefully."}, {"text": "(6, 4)", "feedback": "The sign of the vertex''s y-coordinate is flipped — the constant at the end is the vertex''s y-coordinate exactly as written."}, {"text": "(-4, 6)", "feedback": "The x- and y-coordinates of the vertex are swapped."}, {"text": "(6, -4)", "feedback": "Correct. In vertex form, the vertex is (h, k); here the vertex is (6, -4)."}]'::jsonb,
 'vertex-from-vertex-form'),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 13, 'Medium',
 'What is the vertex of y = (x - 1)(x - 9)?', 2,
 '[
   {"text": "(4, -15)", "feedback": "The axis is halfway between 1 and 9, which is 5, not 4."},
   {"text": "(5, 16)", "feedback": "Substitute x = 5 into both brackets and multiply — one bracket comes out negative."},
   {"text": "(5, -16)", "feedback": "Correct."},
   {"text": "(1, 9)", "feedback": "Those are the x-intercepts bundled into a point. The vertex x is their average."}
 ]'::jsonb,
 null),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 14, 'Medium',
 'A parabola in factored form is y = 2(x + 3)(x - 1). What is its y-intercept?', 0,
 '[
   {"text": "-6", "feedback": "Correct."},
   {"text": "-3", "feedback": "The 2 out front multiplies too: 2 times 3 times -1."},
   {"text": "6", "feedback": "Substituting x = 0 gives 2(3)(-1), and the product of a positive and a negative is negative."},
   {"text": "2", "feedback": "2 is the stretch factor. Substitute x = 0 through the WHOLE equation."}
 ]'::jsonb,
 null),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 15, 'Medium',
 'Which equation has x-intercepts at -2 and 6 and opens downward?', 3,
 '[
   {"text": "y = -(x - 2)(x + 6)", "feedback": "Those brackets zero at +2 and -6 — the intercepts flipped."},
   {"text": "y = (x + 2)(x - 6)", "feedback": "The intercepts are right, but a positive a opens UP."},
   {"text": "y = -(x - 2)(x - 6)", "feedback": "The first bracket zeroes at +2, not -2. An intercept of -2 needs (x + 2)."},
   {"text": "y = -(x + 2)(x - 6)", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 16, 'Challenge',
 'A parabola in standard form is y = x² − 6x + 8. Find its x-intercepts by factoring.', 0,
 '[{"text": "x = 2 and x = 4", "feedback": "Correct. Factoring x²−6x+8 gives (x−2)(x−4), since −2 and −4 multiply to 8 and add to −6; setting each factor to 0 gives x=2 and x=4."}, {"text": "x = −2 and x = −4", "feedback": "Both signs are flipped — the two numbers used in factoring are −2 and −4, but the x-intercepts themselves come from setting (x−2)=0 and (x−4)=0, giving positive roots."}, {"text": "x = 2 and x = −4", "feedback": "Check this pair by expanding (x−2)(x+4) — it gives x²+2x−8, which doesn''t match the original x²−6x+8."}, {"text": "x = 8 and x = 1", "feedback": "These don''t come from factoring x²−6x+8 — find two numbers that multiply to 8 and add to −6, not numbers related to 8 and the coefficient of x another way."}]'::jsonb,
 'x-intercepts-from-standard-form'),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 17, 'Challenge',
 'A parabola in standard form is y = x² - x - 12. Find its x-intercepts by factoring.', 2,
 '[{"text": "x = -4 and x = 3", "feedback": "Both signs are flipped — recheck the zero-product property on each factor individually."}, {"text": "x = 4 and x = -3", "feedback": "One of the two signs is off — substitute both values back into x²-x-12 to check."}, {"text": "x = 4 and x = -3, since x² - x - 12 = (x - 4)(x + 3)", "feedback": "Correct. Factoring x²-x-12 gives (x-4)(x+3), since -4 and 3 multiply to -12 and add to -1; setting each factor to 0 gives x=4 and x=-3."}, {"text": "x = 12 and x = -1", "feedback": "These don''t come from factoring x²-x-12 — find two numbers that multiply to -12 and add to -1, not values related to 12 and 1 directly."}]'::jsonb,
 'x-intercepts-from-standard-form'),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 18, 'Challenge',
 'A parabola in standard form is y = x² + 7x + 10. Find its x-intercepts by factoring.', 0,
 '[{"text": "x = -2 and x = -5", "feedback": "Correct. Factoring x²+7x+10 gives (x+2)(x+5), since 2 and 5 multiply to 10 and add to 7; setting each factor to 0 gives x=-2 and x=-5."}, {"text": "x = 2 and x = 5", "feedback": "Both signs are flipped — recheck the zero-product property on each factor individually."}, {"text": "x = -2 and x = 5", "feedback": "One of the two signs is off — substitute both values back into x²+7x+10 to check."}, {"text": "x = 7 and x = 10", "feedback": "These reuse the equation''s own coefficients directly instead of factoring x²+7x+10."}]'::jsonb,
 'x-intercepts-from-standard-form'),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 19, 'Challenge',
 'A parabola in standard form is y = x² - 9. Find its x-intercepts by factoring.', 3,
 '[{"text": "x = 9 and x = -9", "feedback": "This treats 9 as if it were the roots directly — factor x²-9 as a difference of squares first."}, {"text": "x = 3 only", "feedback": "A parabola with two distinct x-intercepts crosses the x-axis twice — x²-9 factors into two different linear factors."}, {"text": "x = 81", "feedback": "This squares 9 instead of taking its square root — x²-9 is a difference of squares, x²-3²."}, {"text": "x = 3 and x = -3", "feedback": "Correct. x²-9 is a difference of squares, factoring as (x-3)(x+3); setting each factor to 0 gives x=3 and x=-3."}]'::jsonb,
 'x-intercepts-difference-of-squares'),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 20, 'Challenge',
 'A parabola in standard form is y = x² + 4x - 5. Find its x-intercepts by factoring.', 1,
 '[{"text": "x = 5 and x = -1", "feedback": "Both signs are flipped — recheck the zero-product property on each factor individually."}, {"text": "x = -5 and x = 1", "feedback": "Correct. Factoring x²+4x-5 gives (x+5)(x-1), since 5 and -1 multiply to -5 and add to 4; setting each factor to 0 gives x=-5 and x=1."}, {"text": "x = 5 and x = 1", "feedback": "One of the two signs is off — substitute both values back into x²+4x-5 to check."}, {"text": "x = 4 and x = -5", "feedback": "This reuses the coefficient of x directly as one of the roots — find two numbers that multiply to -5 and add to 4 instead."}]'::jsonb,
 'x-intercepts-from-standard-form'),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 21, 'Challenge',
 'A quadratic has x-intercepts -3 and 5 and passes through (1, -32). What is a in factored form?', 3,
 '[
   {"text": "-2", "feedback": "Substitute (1, -32): both the y value AND the bracket product come out negative, and their quotient is positive."},
   {"text": "1/2", "feedback": "-32 divides by -16 — the division went the wrong way."},
   {"text": "-32", "feedback": "-32 is the y value of the point, not the stretch factor. Substitute and solve for a."},
   {"text": "2", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 22, 'Advanced',
 'A parabola has x-intercepts at x = −1 and x = 5, and passes through the point (2, −9). What is its equation in factored form?', 3,
 '[{"text": "y = (x + 1)(x − 5)", "feedback": "This matches the x-intercepts, but check it against the point (2, −9) — without a leading coefficient a, it gives −9 already... verify a is actually needed by substituting."}, {"text": "y = 2(x + 1)(x − 5)", "feedback": "Substituting x = 2 gives y = 2(3)(−3) = −18, not −9 — recheck the value of a."}, {"text": "y = −(x + 1)(x − 5)", "feedback": "Substituting x = 2 gives y = −(3)(−3) = 9, not −9 — the sign of a needs to be positive here."}, {"text": "y = (x + 1)(x − 5), confirmed since a = 1", "feedback": "Correct. Using y = a(x+1)(x−5) and substituting (2, −9): −9 = a(3)(−3) = −9a, so a = 1, giving y = (x+1)(x−5)."}]'::jsonb,
 'factored-form-from-intercepts-and-point'),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 23, 'Advanced',
 'A parabola has x-intercepts at x = 2 and x = 4, and passes through the point (3, -3). What is its equation in factored form?', 1,
 '[{"text": "y = (x - 2)(x - 4)", "feedback": "Substituting x = 3 gives y = (1)(-1) = -1, not -3 — a leading coefficient a is still needed."}, {"text": "y = 3(x - 2)(x - 4)", "feedback": "Correct. Using y = a(x-2)(x-4) and substituting (3, -3): -3 = a(1)(-1) = -a, so a = 3."}, {"text": "y = -3(x - 2)(x - 4)", "feedback": "Substituting x = 3 gives y = -3(1)(-1) = 3, not -3 — recheck the sign of a."}, {"text": "y = 2(x - 2)(x - 4)", "feedback": "Substituting x = 3 gives y = 2(1)(-1) = -2, not -3 — recheck solving -3 = a(1)(-1) for a."}]'::jsonb,
 'factored-form-from-intercepts-and-point'),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 24, 'Advanced',
 'A parabola has x-intercepts at x = -3 and x = 1, and passes through the point (0, -9). What is its equation in factored form?', 2,
 '[{"text": "y = (x + 3)(x - 1)", "feedback": "Substituting x = 0 gives y = (3)(-1) = -3, not -9 — a leading coefficient a is still needed."}, {"text": "y = -3(x + 3)(x - 1)", "feedback": "Substituting x = 0 gives y = -3(3)(-1) = 9, not -9 — recheck the sign of a."}, {"text": "y = 3(x + 3)(x - 1)", "feedback": "Correct. Using y = a(x+3)(x-1) and substituting (0, -9): -9 = a(3)(-1) = -3a, so a = 3."}, {"text": "y = 9(x + 3)(x - 1)", "feedback": "Substituting x = 0 gives y = 9(3)(-1) = -27, not -9 — recheck solving -9 = a(3)(-1) for a."}]'::jsonb,
 'factored-form-from-intercepts-and-point'),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 25, 'Advanced',
 'A parabola has vertex (2, -8) and passes through the point (0, 0). What is its equation in vertex form?', 3,
 '[{"text": "y = (x - 2)² - 8", "feedback": "Substituting x = 0 gives y = 4 - 8 = -4, not 0 — a leading coefficient a is still needed."}, {"text": "y = -2(x - 2)² - 8", "feedback": "Substituting x = 0 gives y = -2(4) - 8 = -16, not 0 — recheck the sign and value of a."}, {"text": "y = 8(x - 2)² - 8", "feedback": "Substituting x = 0 gives y = 8(4) - 8 = 24, not 0 — recheck solving 0 = 4a - 8 for a."}, {"text": "y = 2(x - 2)² - 8", "feedback": "Correct. Using y = a(x-2)²-8 and substituting (0, 0): 0 = a(0-2)²-8 = 4a-8, so a = 2."}]'::jsonb,
 'vertex-form-from-point'),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 26, 'Advanced',
 'A parabola has x-intercepts at x = -2 and x = 6, and a y-intercept of -24. What is its equation in factored form?', 1,
 '[{"text": "y = (x + 2)(x - 6)", "feedback": "Substituting x = 0 gives y = (2)(-6) = -12, not -24 — a leading coefficient a is still needed."}, {"text": "y = 2(x + 2)(x - 6)", "feedback": "Correct. Using y = a(x+2)(x-6) and substituting the y-intercept (0, -24): -24 = a(2)(-6) = -12a, so a = 2."}, {"text": "y = -2(x + 2)(x - 6)", "feedback": "Substituting x = 0 gives y = -2(2)(-6) = 24, not -24 — recheck the sign of a."}, {"text": "y = 12(x + 2)(x - 6)", "feedback": "Substituting x = 0 gives y = 12(2)(-6) = -144, not -24 — recheck solving -24 = a(2)(-6) for a."}]'::jsonb,
 'factored-form-from-intercepts-and-y-intercept'),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 27, 'Advanced',
 'A rectangular pen uses 40 m of fence. Its area is A = w(20 - w). What width gives the maximum area?', 2,
 '[
   {"text": "20 m", "feedback": "w = 20 makes the OTHER side zero — no pen at all. The best width sits midway between the two zeros."},
   {"text": "5 m", "feedback": "Compare areas: at w = 5 the pen is long and thin. The vertex sits midway between the zeros of w(20 - w)."},
   {"text": "10 m", "feedback": "Correct."},
   {"text": "40 m", "feedback": "40 is the whole fence. The two widths together use only part of it."}
 ]'::jsonb,
 null),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 28, 'Advanced',
 'A rectangular pen uses 40 m of fence, so its area is A = w(20 - w). What is the maximum area of that pen?', 1,
 '[
   {"text": "400 m²", "feedback": "400 is 20 squared. Substitute the best width into w(20 - w) instead."},
   {"text": "100 m²", "feedback": "Correct."},
   {"text": "75 m²", "feedback": "That is the area at w = 5, not at the vertex."},
   {"text": "200 m²", "feedback": "That multiplies the best width by the FULL 20. The other side of the pen is 20 minus w."}
 ]'::jsonb,
 null),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 29, 'Advanced',
 'A quadratic has vertex (1, -8) and one x-intercept at 3. Where is the other x-intercept?', 2,
 '[
   {"text": "-3", "feedback": "Mirror across the axis x = 1, not across the y-axis. Measure how far 3 sits from the axis, then go that same distance the other way."},
   {"text": "5", "feedback": "Intercepts mirror across the AXIS x = 1. Reflecting 3 puts the other one on the far side of the axis, not further right."},
   {"text": "-1", "feedback": "Correct."},
   {"text": "8", "feedback": "8 comes from the vertex height, which does not locate intercepts."}
 ]'::jsonb,
 null),
('MPM2D', 'quadratics', 'factored-form-and-zeros', 30, 'Advanced',
 'Two numbers add to 14. What is the largest their product can be?', 2,
 '[
   {"text": "48", "feedback": "Close but under — that is 6 times 8. The true peak sits at the vertex of n(14 - n), where the two numbers are equal."},
   {"text": "196", "feedback": "196 is 14 squared — but the two numbers ADD to 14, they are not both 14."},
   {"text": "49", "feedback": "Correct."},
   {"text": "14", "feedback": "14 is the sum, given. Find the vertex of the product n(14 - n)."}
 ]'::jsonb,
 null),
('MPM2D', 'trigonometry', 'sine-law', 1, 'Easy',
 'Which situation requires the sine law rather than the cosine law to solve a triangle?', 1,
 '[{"text": "You know all three side lengths (SSS)", "feedback": "Knowing all three sides with no angles is exactly when the cosine law is needed — the sine law needs at least one known angle-side pair."}, {"text": "You know two angles and one side (AAS or ASA)", "feedback": "Correct. The sine law needs a complete angle-side pair (a known angle and the side directly opposite it) somewhere in the triangle, which two known angles and one side always provides."}, {"text": "You know two sides and the angle between them (SAS)", "feedback": "The angle here isn''t opposite either of the two known sides, so there''s no complete pair for the sine law — that''s a cosine law situation."}, {"text": "You know two sides and the angle between them, and none of the angles", "feedback": "This describes SAS, which is exactly the situation the cosine law is designed to solve, not the sine law."}]'::jsonb,
 'sine-law-vs-cosine-law-conditions'),
('MPM2D', 'trigonometry', 'sine-law', 2, 'Easy',
 'In the sine law, a/sin A = b/sin B = c/sin C, what must a side and the angle paired with it in the same fraction have in common?', 1,
 '[{"text": "They must both be the largest in the triangle", "feedback": "The sine law pairs a side with an angle regardless of size — the key requirement is about their position in the triangle, not which is largest."}, {"text": "The angle must be directly opposite that side", "feedback": "Correct. Each fraction in the sine law pairs a side with the angle sitting directly across from it in the triangle."}, {"text": "They must be adjacent to each other", "feedback": "The angle paired with a side in the sine law is the one opposite it, not one of the two angles touching that side."}, {"text": "The angle must be acute", "feedback": "The sine law works with any angle, acute or obtuse — what matters is that the angle is opposite the paired side, not its size."}]'::jsonb,
 'sine-law-formula-structure'),
('MPM2D', 'trigonometry', 'sine-law', 3, 'Easy',
 'You know two angles of a triangle and one side. Which law should you use to find a missing side?', 0,
 '[{"text": "The sine law", "feedback": "Correct. Knowing two angles and one side gives a complete angle-side pair (the known side and its opposite angle), which the sine law needs."}, {"text": "The cosine law", "feedback": "The cosine law is used when you know two sides and the included angle, or all three sides — not two angles and one side."}, {"text": "The Pythagorean theorem", "feedback": "The Pythagorean theorem only applies to right triangles — there''s no indication this triangle has a right angle."}, {"text": "The quadratic formula", "feedback": "The quadratic formula solves equations of the form ax²+bx+c=0 — it has no role in solving a triangle for a missing side."}]'::jsonb,
 'sine-law-vs-cosine-law-conditions'),
('MPM2D', 'trigonometry', 'sine-law', 4, 'Easy',
 'In a triangle, angle A = 50° and angle B = 70°. What is angle C?', 2,
 '[{"text": "130°", "feedback": "This adds A and B together without subtracting from 180° — the three angles of a triangle sum to 180°."}, {"text": "50°", "feedback": "This just reuses angle A — find C by subtracting both given angles from 180°."}, {"text": "60°", "feedback": "Correct. The three angles of a triangle always sum to 180°, so C = 180° − 50° − 70° = 60°."}, {"text": "120°", "feedback": "This subtracts only one of the two given angles from 180° — both A and B need to be subtracted."}]'::jsonb,
 'triangle-angle-sum'),
('MPM2D', 'trigonometry', 'sine-law', 5, 'Easy',
 'In a triangle with sides a, b, c opposite angles A, B, C, which of these is a correctly written sine law equation?', 1,
 '[{"text": "a/sin B = b/sin A", "feedback": "Each side should be paired with its *own* opposite angle — a with A, and b with B, not swapped."}, {"text": "a/sin A = b/sin B", "feedback": "Correct. The sine law pairs each side with the angle directly opposite it: a with A, and b with B."}, {"text": "sin A/a = sin B/c", "feedback": "This mixes side b''s opposite angle (B) with side c''s own letter — each side should be paired only with its own opposite angle."}, {"text": "a × sin A = b × sin B", "feedback": "The sine law is a ratio (division), not a product — each side is divided by the sine of its opposite angle."}]'::jsonb,
 'sine-law-formula-structure'),
('MPM2D', 'trigonometry', 'sine-law', 6, 'Easy',
 'The sine law relates what quantities?', 0,
 '[
   {"text": "Each side to the sine of its opposite angle", "feedback": "Correct."},
   {"text": "The two legs and the hypotenuse", "feedback": "Legs and hypotenuse language belongs to RIGHT triangles. The sine law works on any triangle."},
   {"text": "Each side to the sine of its adjacent angle", "feedback": "The pairing is strictly OPPOSITE: a with A, across the triangle."},
   {"text": "The three angles only", "feedback": "Angles alone come from the 180° sum. The sine law brings the sides in."}
 ]'::jsonb,
 null),
('MPM2D', 'trigonometry', 'sine-law', 7, 'Medium',
 'In a triangle, angle A = 40°, side a = 10, and angle B = 65°. What is the length of side b, to one decimal place?', 3,
 '[{"text": "b ≈ 10.8", "feedback": "This doesn''t come from a÷sin(A) = b÷sin(B) — recheck by cross-multiplying: b = 10 × sin(65°) ÷ sin(40°)."}, {"text": "b ≈ 6.2", "feedback": "This looks like sin(A) and sin(B) were swapped in the ratio — side b should come out larger than side a, since angle B is bigger than angle A."}, {"text": "b ≈ 15.6", "feedback": "This is larger than the correct value — double check that sin(65°) and sin(40°) were placed correctly in the ratio b = a×sin(B)÷sin(A)."}, {"text": "b ≈ 14.1", "feedback": "Correct. By the sine law, a÷sin(A) = b÷sin(B), so b = 10 × sin(65°) ÷ sin(40°) ≈ 14.1."}]'::jsonb,
 'sine-law-solve-for-side'),
('MPM2D', 'trigonometry', 'sine-law', 8, 'Medium',
 'In a triangle, angle A = 55°, side a = 12, and angle B = 70°. What is the length of side b, to one decimal place?', 3,
 '[{"text": "b ≈ 10.5", "feedback": "This doesn''t come from a÷sin(A) = b÷sin(B) — recheck by cross-multiplying: b = 12 × sin(70°) ÷ sin(55°)."}, {"text": "b ≈ 8.2", "feedback": "This looks like sin(A) and sin(B) were swapped in the ratio — side b should come out larger than side a, since angle B is bigger than angle A."}, {"text": "b ≈ 16.9", "feedback": "This is larger than the correct value — double check that sin(70°) and sin(55°) were placed correctly in the ratio."}, {"text": "b ≈ 13.8", "feedback": "Correct. By the sine law, a÷sin(A) = b÷sin(B), so b = 12 × sin(70°) ÷ sin(55°) ≈ 13.8."}]'::jsonb,
 'sine-law-solve-for-side'),
('MPM2D', 'trigonometry', 'sine-law', 9, 'Medium',
 'In a triangle, angle A = 30°, side a = 8, and angle C = 100°. What is the length of side c, to one decimal place?', 1,
 '[{"text": "c ≈ 4.1", "feedback": "This looks like sin(A) and sin(C) were swapped in the ratio — side c should come out larger than side a, since angle C is much bigger than angle A."}, {"text": "c ≈ 15.8", "feedback": "Correct. By the sine law, a÷sin(A) = c÷sin(C), so c = 8 × sin(100°) ÷ sin(30°) ≈ 15.8."}, {"text": "c ≈ 26.7", "feedback": "This is too large — double check that sin(100°) and sin(30°) were placed correctly in the ratio."}, {"text": "c ≈ 8.0", "feedback": "This just reuses side a — apply the sine law ratio to find the actual value of c."}]'::jsonb,
 'sine-law-solve-for-side'),
('MPM2D', 'trigonometry', 'sine-law', 10, 'Medium',
 'In a triangle, angle B = 45°, side b = 20, and angle A = 60°. What is the length of side a, to one decimal place?', 0,
 '[{"text": "a ≈ 24.5", "feedback": "Correct. By the sine law, a÷sin(A) = b÷sin(B), so a = 20 × sin(60°) ÷ sin(45°) ≈ 24.5."}, {"text": "a ≈ 16.3", "feedback": "This looks like sin(A) and sin(B) were swapped in the ratio — side a should come out larger than side b, since angle A is bigger than angle B."}, {"text": "a ≈ 20.0", "feedback": "This just reuses side b — apply the sine law ratio to find the actual value of a."}, {"text": "a ≈ 30.0", "feedback": "This is too large — double check that sin(60°) and sin(45°) were placed correctly in the ratio."}]'::jsonb,
 'sine-law-solve-for-side'),
('MPM2D', 'trigonometry', 'sine-law', 11, 'Medium',
 'In a triangle, angle C = 80°, side c = 25, and angle B = 35°. What is the length of side b, to one decimal place?', 2,
 '[{"text": "b ≈ 25.0", "feedback": "This just reuses side c — apply the sine law ratio to find the actual value of b."}, {"text": "b ≈ 35.7", "feedback": "This is too large — double check that sin(35°) and sin(80°) were placed correctly in the ratio."}, {"text": "b ≈ 14.6", "feedback": "Correct. By the sine law, b÷sin(B) = c÷sin(C), so b = 25 × sin(35°) ÷ sin(80°) ≈ 14.6."}, {"text": "b ≈ 43.5", "feedback": "This looks like sin(B) and sin(C) were swapped in the ratio — side b should come out smaller than side c, since angle B is smaller than angle C."}]'::jsonb,
 'sine-law-solve-for-side'),
('MPM2D', 'trigonometry', 'sine-law', 12, 'Medium',
 'In triangle ABC, angle A = 40°, angle B = 75°, and b = 12 cm. What is side a, to one decimal?', 0,
 '[
   {"text": "8.0 cm", "feedback": "Correct."},
   {"text": "7.7 cm", "feedback": "The sin 75° divisor went missing. The sine law is a full proportion, not one product."},
   {"text": "18.0 cm", "feedback": "The sines are flipped — the unknown side sits on top, multiplied by the sine of ITS OWN opposite angle."},
   {"text": "12.0 cm", "feedback": "Side a faces the SMALLER angle, so it must come out shorter than 12."}
 ]'::jsonb,
 null),
('MPM2D', 'trigonometry', 'sine-law', 13, 'Medium',
 'In triangle ABC, a = 9, b = 14 and angle B = 80°. What is angle A, to one decimal?', 0,
 '[
   {"text": "39.3°", "feedback": "Correct."},
   {"text": "0.6°", "feedback": "That is the sine RATIO, not the angle. The inverse sine still has to run."},
   {"text": "39.1°", "feedback": "That rounds the sine ratio to two decimals before the inverse sine. Keep the digits until the end."},
   {"text": "61.0°", "feedback": "That subtracts from 180 too early: find A from the sine law first, then any leftover angle."}
 ]'::jsonb,
 null),
('MPM2D', 'trigonometry', 'sine-law', 14, 'Challenge',
 'In a triangle, a = 12, angle A = 35°, and b = 18. What is angle B, to the nearest degree?', 2,
 '[{"text": "B ≈ 23°", "feedback": "This is smaller than angle A, but side b (18) is longer than side a (12) — the larger side should be opposite the larger angle."}, {"text": "B ≈ 35°", "feedback": "This just reuses angle A''s value — since sides a and b have different lengths, angles A and B must also differ."}, {"text": "B ≈ 59°", "feedback": "Correct. By the sine law, sin(B)÷b = sin(A)÷a, so sin(B) = 18 × sin(35°) ÷ 12 ≈ 0.860, giving B ≈ sin⁻¹(0.860) ≈ 59°."}, {"text": "B ≈ 86°", "feedback": "This is too large for this triangle — recheck the ratio sin(B) = b × sin(A) ÷ a before taking the inverse sine."}]'::jsonb,
 'sine-law-solve-for-angle'),
('MPM2D', 'trigonometry', 'sine-law', 15, 'Challenge',
 'In a triangle, side a = 10, angle A = 40°, and side b = 14. What is angle B, to the nearest degree?', 3,
 '[{"text": "B ≈ 29°", "feedback": "This is too small for a triangle where side b (14) is longer than side a (10) — the larger side should be opposite the larger angle."}, {"text": "B ≈ 40°", "feedback": "This just reuses angle A''s value — since sides a and b have different lengths, angles A and B must also differ."}, {"text": "B ≈ 78°", "feedback": "This is too large for this triangle — recheck the ratio sin(B) = b × sin(A) ÷ a before taking the inverse sine."}, {"text": "B ≈ 64°", "feedback": "Correct. By the sine law, sin(B)÷b = sin(A)÷a, so sin(B) = 14 × sin(40°) ÷ 10 ≈ 0.900, giving B ≈ sin⁻¹(0.900) ≈ 64°."}]'::jsonb,
 'sine-law-solve-for-angle'),
('MPM2D', 'trigonometry', 'sine-law', 16, 'Challenge',
 'In a triangle, side a = 15, angle A = 25°, and side c = 20. What is angle C, to the nearest degree?', 1,
 '[{"text": "C ≈ 19°", "feedback": "This is too small — side c (20) is longer than side a (15), so angle C should be larger than angle A (25°), not smaller."}, {"text": "C ≈ 34°", "feedback": "Correct. By the sine law, sin(C)÷c = sin(A)÷a, so sin(C) = 20 × sin(25°) ÷ 15 ≈ 0.563, giving C ≈ sin⁻¹(0.563) ≈ 34°."}, {"text": "C ≈ 25°", "feedback": "This just reuses angle A''s value — since sides a and c have different lengths, angles A and C must also differ."}, {"text": "C ≈ 51°", "feedback": "This is too large for this triangle — recheck the ratio sin(C) = c × sin(A) ÷ a before taking the inverse sine."}]'::jsonb,
 'sine-law-solve-for-angle'),
('MPM2D', 'trigonometry', 'sine-law', 17, 'Challenge',
 'In a triangle, side b = 18, angle B = 55°, and side a = 14. What is angle A, to the nearest degree?', 2,
 '[{"text": "A ≈ 55°", "feedback": "This just reuses angle B''s value — since sides a and b have different lengths, angles A and B must also differ."}, {"text": "A ≈ 51°", "feedback": "Recheck the ratio sin(A) = a × sin(B) ÷ b — this doesn''t quite match that calculation."}, {"text": "A ≈ 40°", "feedback": "Correct. By the sine law, sin(A)÷a = sin(B)÷b, so sin(A) = 14 × sin(55°) ÷ 18 ≈ 0.637, giving A ≈ sin⁻¹(0.637) ≈ 40°."}, {"text": "A ≈ 71°", "feedback": "This is too large for this triangle — side a (14) is shorter than side b (18), so angle A should be smaller than angle B (55°), not larger."}]'::jsonb,
 'sine-law-solve-for-angle'),
('MPM2D', 'trigonometry', 'sine-law', 18, 'Challenge',
 'In a triangle, side c = 22, angle C = 65°, and side a = 17. What is angle A, to the nearest degree?', 0,
 '[{"text": "A ≈ 44°", "feedback": "Correct. By the sine law, sin(A)÷a = sin(C)÷c, so sin(A) = 17 × sin(65°) ÷ 22 ≈ 0.700, giving A ≈ sin⁻¹(0.700) ≈ 44°."}, {"text": "A ≈ 65°", "feedback": "This just reuses angle C''s value — since sides a and c have different lengths, angles A and C must also differ."}, {"text": "A ≈ 84°", "feedback": "This is too large for this triangle — side a (17) is shorter than side c (22), so angle A should be smaller than angle C (65°), not larger."}, {"text": "A ≈ 36°", "feedback": "Recheck the ratio sin(A) = a × sin(C) ÷ c — this doesn''t quite match that calculation."}]'::jsonb,
 'sine-law-solve-for-angle'),
('MPM2D', 'trigonometry', 'sine-law', 19, 'Challenge',
 'In triangle ABC, angle A = 35°, angle B = 65°, and a = 10 cm. What is side c, to one decimal?', 2,
 '[
   {"text": "5.8 cm", "feedback": "The proportion is upside down: c = a sin C over sin A, with the unknown side on top."},
   {"text": "15.8 cm", "feedback": "That found side b. Side c pairs with angle C, which is 180 - 35 - 65 = 80°."},
   {"text": "17.2 cm", "feedback": "Correct."},
   {"text": "10.0 cm", "feedback": "c faces the LARGEST angle, 80°, so it must be the longest side — longer than 10."}
 ]'::jsonb,
 null),
('MPM2D', 'trigonometry', 'sine-law', 20, 'Advanced',
 'In a triangle, angle A = 50°, angle B = 60°, and side a = 8. What is side c, to one decimal place?', 1,
 '[{"text": "c ≈ 8.7", "feedback": "This looks like it used angle B instead of angle C — first find angle C = 180°−50°−60° = 70°, then use that in the sine law ratio."}, {"text": "c ≈ 9.8", "feedback": "Correct. First find angle C = 180° − 50° − 60° = 70°. Then by the sine law, c÷sin(C) = a÷sin(A), so c = 8 × sin(70°) ÷ sin(50°) ≈ 9.8."}, {"text": "c ≈ 6.5", "feedback": "This looks like sin(A) and sin(C) were swapped in the ratio — since angle C (70°) is larger than angle A (50°), side c should come out larger than side a, not smaller."}, {"text": "c ≈ 11.0", "feedback": "Double-check angle C: it should be 180° minus the other two given angles, 50° and 60°, which gives 70°, not a different value."}]'::jsonb,
 'sine-law-third-angle-first'),
('MPM2D', 'trigonometry', 'sine-law', 21, 'Advanced',
 'In a triangle, angle A = 42°, angle B = 63°, and side a = 9. What is the length of side c, to one decimal place?', 2,
 '[{"text": "c ≈ 9.0", "feedback": "This just reuses side a — angle C needs to be found first, then the sine law applied between a and c."}, {"text": "c ≈ 8.0", "feedback": "This is too small — first find angle C = 180°−42°−63° = 75°, then use it in the sine law ratio."}, {"text": "c ≈ 13.0", "feedback": "Correct. First find angle C = 180° − 42° − 63° = 75°. Then by the sine law, c÷sin(C) = a÷sin(A), so c = 9 × sin(75°) ÷ sin(42°) ≈ 13.0."}, {"text": "c ≈ 16.9", "feedback": "This looks like angle A and angle C were swapped in the ratio — recompute c = a × sin(C) ÷ sin(A) with C = 75°."}]'::jsonb,
 'sine-law-third-angle-first'),
('MPM2D', 'trigonometry', 'sine-law', 22, 'Advanced',
 'In a triangle, angle A = 38°, angle C = 79°, and side c = 30. What is the length of side b, to one decimal place?', 3,
 '[{"text": "b ≈ 30.0", "feedback": "This just reuses side c — angle B needs to be found first, then the sine law applied between b and c."}, {"text": "b ≈ 18.8", "feedback": "This is too small — first find angle B = 180°−38°−79° = 63°, then use it in the sine law ratio with side c."}, {"text": "b ≈ 23.5", "feedback": "Recheck the setup: first find angle B = 180°−38°−79° = 63°, then compute b = c × sin(B) ÷ sin(C)."}, {"text": "b ≈ 27.2", "feedback": "Correct. First find angle B = 180° − 38° − 79° = 63°. Then by the sine law, b÷sin(B) = c÷sin(C), so b = 30 × sin(63°) ÷ sin(79°) ≈ 27.2."}]'::jsonb,
 'sine-law-third-angle-first'),
('MPM2D', 'trigonometry', 'sine-law', 23, 'Advanced',
 'A triangle has side a = 10, side b = 14, and angle A = 40°. How many different triangles are possible?', 1,
 '[{"text": "Exactly one", "feedback": "Check the ambiguous case carefully: the height h = b×sin(A) ≈ 9.0 is less than a (10), which is itself less than b (14) — that combination allows for two triangles, not just one."}, {"text": "Two", "feedback": "Correct. This is the ambiguous (SSA) case: h = b×sin(A) = 14×sin(40°) ≈ 9.0; since h < a (10) < b (14), there are two possible triangles — one with angle B acute, and one with angle B obtuse."}, {"text": "Zero — no triangle is possible", "feedback": "A triangle is possible here — in fact, this exact combination of a shorter given side allows for *two* valid triangles, not zero."}, {"text": "Three", "feedback": "The ambiguous case (SSA) can produce at most two distinct triangles, never three."}]'::jsonb,
 'sine-law-ambiguous-case'),
('MPM2D', 'trigonometry', 'sine-law', 24, 'Advanced',
 'In a triangle, angle A = 55°, angle B = 75°, and side b = 40. Find the triangle''s perimeter, to one decimal place.', 0,
 '[{"text": "≈ 105.6", "feedback": "Correct. First find angle C = 180°−55°−75° = 50°. Then a = 40×sin(55°)÷sin(75°) ≈ 33.9, and c = 40×sin(50°)÷sin(75°) ≈ 31.7; the perimeter is a+b+c ≈ 33.9+40+31.7 ≈ 105.6."}, {"text": "≈ 120.0", "feedback": "This doesn''t come from computing a and c using the sine law with angle C = 50° — recompute both missing sides individually first."}, {"text": "≈ 80.0", "feedback": "This only doubles side b — the other two sides, a and c, need to be found using the sine law before adding everything together."}, {"text": "≈ 91.2", "feedback": "Recheck the value of angle C (180°−55°−75° = 50°) and the resulting side lengths a and c before summing all three sides."}]'::jsonb,
 'sine-law-solve-for-perimeter'),
('MPM2D', 'trigonometry', 'sine-law', 25, 'Advanced',
 'In triangle ABC, angle A = 100°, a = 14 and angle B = 35°. What is b, to one decimal?', 3,
 '[
   {"text": "0.6", "feedback": "That is the ratio of the two sines alone. The 14 still multiplies it."},
   {"text": "24.0", "feedback": "The proportion is inverted — that value comes out LONGER than 14, impossible opposite a smaller angle."},
   {"text": "10.1", "feedback": "45 is angle C, from the 180° sum — the wrong partner for side b. Side b pairs with angle B."},
   {"text": "8.2", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'trigonometry', 'sine-law', 26, 'Advanced',
 'A triangle problem gives sides a and b and angle A, opposite side a. Which tool starts the solution?', 3,
 '[
   {"text": "The cosine law, because two sides are known", "feedback": "Two sides feed the cosine law only WITH the contained angle. Angle A here is opposite a, which is a sine law pairing."},
   {"text": "Neither — more information is needed", "feedback": "A matched pair plus one more side is exactly the sine law setup for finding angle B."},
   {"text": "SOH CAH TOA", "feedback": "No right angle was given, so the primary ratios cannot apply."},
   {"text": "The sine law, because a side-opposite-angle pair is known", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'trigonometry', 'cosine-law', 1, 'Easy',
 'The cosine law is used to find a missing side when you know:', 2,
 '[{"text": "Two angles and one side", "feedback": "This situation (AAS or ASA) has a complete angle-side pair, which is exactly what the sine law is designed for instead."}, {"text": "One angle and the two sides adjacent to a different angle", "feedback": "This description doesn''t match a standard triangle case — the cosine law specifically needs the angle sandwiched directly between the two known sides."}, {"text": "Two sides and the angle between them (SAS)", "feedback": "Correct. The cosine law formula, like c² = a²+b²−2ab·cos(C), needs two known sides and the included angle between them to solve for the third side."}, {"text": "Three angles only", "feedback": "Knowing only three angles (with no side lengths) isn''t enough to find any actual side length — similar triangles of many different sizes could share those same three angles."}]'::jsonb,
 'cosine-law-vs-sine-law-conditions'),
('MPM2D', 'trigonometry', 'cosine-law', 2, 'Easy',
 'A triangle has all three angles measuring less than 90°. What type of triangle is this?', 2,
 '[{"text": "Obtuse", "feedback": "An obtuse triangle has one angle greater than 90° — the opposite of what''s described here."}, {"text": "Right", "feedback": "A right triangle has exactly one angle equal to 90° — here, every angle is strictly less than 90°."}, {"text": "Acute", "feedback": "Correct. A triangle with all three angles under 90° is called an acute triangle."}, {"text": "Isosceles", "feedback": "Isosceles describes a triangle with two equal sides, which is about side lengths, not the size of the angles."}]'::jsonb,
 'acute-triangle-definition'),
('MPM2D', 'trigonometry', 'cosine-law', 3, 'Easy',
 'In the cosine law formula c² = a² + b² - 2ab·cos(C), which angle does C represent?', 1,
 '[{"text": "Any one of the triangle''s three angles", "feedback": "C specifically refers to the angle opposite side c — it isn''t an arbitrary choice among the three angles."}, {"text": "The angle between sides a and b, opposite side c", "feedback": "Correct. C is the included angle, sitting between the two known sides a and b, and it''s opposite the side (c) being solved for."}, {"text": "The smallest angle in the triangle", "feedback": "C isn''t defined by being the smallest angle — it''s specifically the angle opposite side c, whatever its size happens to be."}, {"text": "The angle opposite side a", "feedback": "The angle opposite side a is A, not C — C is opposite side c, the side the formula is solving for."}]'::jsonb,
 'cosine-law-formula-structure'),
('MPM2D', 'trigonometry', 'cosine-law', 4, 'Easy',
 'You know all three side lengths of a triangle (SSS). Which law can find a missing angle?', 2,
 '[{"text": "The sine law", "feedback": "The sine law needs a complete angle-side pair (a known angle opposite a known side) to get started — SSS gives no angles at all."}, {"text": "The Pythagorean theorem", "feedback": "The Pythagorean theorem only applies to right triangles — there''s no indication this triangle has a right angle."}, {"text": "The cosine law", "feedback": "Correct. Rearranged to solve for an angle, the cosine law only needs the three side lengths — exactly what SSS provides."}, {"text": "The quadratic formula", "feedback": "The quadratic formula solves equations of the form ax²+bx+c=0 — it has no direct role in finding a triangle''s angle from its three sides."}]'::jsonb,
 'cosine-law-vs-sine-law-conditions'),
('MPM2D', 'trigonometry', 'cosine-law', 5, 'Easy',
 'In the cosine law, when angle C is exactly 90°, what does the formula c² = a² + b² - 2ab·cos(C) simplify to?', 0,
 '[{"text": "The Pythagorean theorem, c² = a² + b²", "feedback": "Correct. Since cos(90°) = 0, the last term (2ab·cos(C)) disappears entirely, leaving exactly the Pythagorean theorem."}, {"text": "c² = a² - b²", "feedback": "This isn''t what happens when cos(90°) = 0 — the whole term 2ab·cos(C) vanishes, not just part of it."}, {"text": "c = a + b", "feedback": "The cosine law works with squared side lengths, not the sides themselves added directly."}, {"text": "c² = 2ab", "feedback": "This keeps only the last term and drops a² and b² entirely — actually the opposite happens: the last term disappears, leaving a²+b²."}]'::jsonb,
 'cosine-law-reduces-to-pythagorean'),
('MPM2D', 'trigonometry', 'cosine-law', 6, 'Easy',
 'Which situation requires the cosine law: knowing all three sides (SSS), or knowing two angles and a side (AAS)?', 0,
 '[{"text": "SSS", "feedback": "Correct. With three sides and no angles, there''s no complete angle-side pair for the sine law — the cosine law (rearranged to solve for an angle) is the tool that works with SSS alone."}, {"text": "AAS", "feedback": "AAS gives a complete angle-side pair (a known angle opposite a known side), which is exactly what the sine law needs — no cosine law required."}, {"text": "Both require the cosine law equally", "feedback": "AAS is a classic sine law situation, since it already provides a matching angle-side pair — only SSS (and SAS) call for the cosine law."}, {"text": "Neither — both need the sine law", "feedback": "SSS has no angles at all, so there''s no angle-side pair to start the sine law with — that''s exactly when the cosine law is needed instead."}]'::jsonb,
 'cosine-law-vs-sine-law-conditions'),
('MPM2D', 'trigonometry', 'cosine-law', 7, 'Easy',
 'An acute triangle has three angles that are all ___ 90°.', 1,
 '[{"text": "greater than", "feedback": "Angles greater than 90° describe an obtuse triangle, not an acute one."}, {"text": "less than", "feedback": "Correct. Every angle in an acute triangle measures less than 90°."}, {"text": "equal to", "feedback": "A triangle with an angle equal to 90° is a right triangle, not an acute one."}, {"text": "a multiple of", "feedback": "There''s no requirement that the angles be multiples of 90° — only that each one is strictly less than 90°."}]'::jsonb,
 'acute-triangle-definition'),
('MPM2D', 'trigonometry', 'cosine-law', 8, 'Easy',
 'Which set of angles could belong to an acute triangle: 50°, 60°, 70° or 40°, 40°, 100°?', 0,
 '[{"text": "50°, 60°, 70°", "feedback": "Correct. All three angles are less than 90°, and they sum to 180°, so this is a valid acute triangle."}, {"text": "40°, 40°, 100°", "feedback": "The 100° angle is greater than 90°, which makes this an obtuse triangle, not an acute one."}, {"text": "Both sets could be acute triangles", "feedback": "The second set includes a 100° angle, which is greater than 90° — that makes it obtuse, not acute."}, {"text": "Neither set is a valid triangle", "feedback": "Both sets of angles actually sum to 180°, so both describe valid triangles — just not both acute ones."}]'::jsonb,
 'acute-triangle-identify-from-angles'),
('MPM2D', 'trigonometry', 'cosine-law', 9, 'Easy',
 'Given only the three side lengths (SSS) of an acute triangle, which law would you use to find one of its angles?', 2,
 '[{"text": "The sine law", "feedback": "The sine law needs a complete angle-side pair (a known angle opposite a known side) to get started — SSS gives no angles at all."}, {"text": "The Pythagorean theorem", "feedback": "The Pythagorean theorem only applies to right triangles — an acute triangle has no right angle."}, {"text": "The cosine law", "feedback": "Correct. Rearranged to solve for an angle, the cosine law only needs the three side lengths — exactly what SSS provides."}, {"text": "The quadratic formula", "feedback": "The quadratic formula solves equations of the form ax²+bx+c=0 — it has no direct role in finding a triangle''s angle from its three sides."}]'::jsonb,
 'acute-triangle-tool-choice'),
('MPM2D', 'trigonometry', 'cosine-law', 10, 'Easy',
 'True or false: every equilateral triangle is an acute triangle.', 0,
 '[{"text": "True", "feedback": "Correct. An equilateral triangle''s three angles are always equal, and since they sum to 180°, each one is exactly 60° — well under 90°, making it acute."}, {"text": "False, because equilateral triangles have no defined angles", "feedback": "Every triangle, equilateral or not, has three well-defined interior angles that sum to 180°."}, {"text": "False, because equilateral triangles are always right triangles", "feedback": "A right triangle needs one angle of exactly 90° — an equilateral triangle''s angles are all 60°, nowhere near 90°."}, {"text": "It depends on the side lengths", "feedback": "An equilateral triangle''s angles are always 60°-60°-60°, regardless of how long its sides are — so it''s always acute."}]'::jsonb,
 'acute-triangle-equilateral-special-case'),
('MPM2D', 'trigonometry', 'cosine-law', 11, 'Easy',
 'In a triangle with no right angle, when is the cosine law needed rather than the sine law?', 3,
 '[
   {"text": "Whenever the triangle has an obtuse angle", "feedback": "An obtuse angle does not decide which law applies. What matters is which sides and angles are given."},
   {"text": "When the triangle is small", "feedback": "Size is irrelevant. The choice of law rests on which parts are known."},
   {"text": "When only angles are known", "feedback": "Only angles fixes the shape but not the size — no law finds sides from angles alone."},
   {"text": "When no side has its opposite angle known", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'trigonometry', 'cosine-law', 12, 'Medium',
 'In a triangle, a = 7, c = 10, and the angle between them, B = 55°. What is the length of side b, to one decimal place?', 0,
 '[{"text": "b ≈ 8.3", "feedback": "Correct. By the cosine law, b² = a²+c²−2ac·cos(B) = 7²+10²−2(7)(10)cos(55°) ≈ 68.7, so b ≈ √68.7 ≈ 8.3."}, {"text": "b ≈ 12.7", "feedback": "This is too large — recheck the subtraction step in b² = a²+c²−2ac·cos(B); the 2ac·cos(B) term should be subtracted, not added."}, {"text": "b ≈ 3.0", "feedback": "This is too small — recompute a²+c² (49+100=149) before subtracting the 2ac·cos(B) term."}, {"text": "b ≈ 68.7", "feedback": "This is b², the value before the final square root — one more step is needed to find b itself."}]'::jsonb,
 'cosine-law-solve-for-side'),
('MPM2D', 'trigonometry', 'cosine-law', 13, 'Medium',
 'A triangular garden has two sides of length 12 m and 15 m, with an included angle of 50°. What is the length of the third side, to the nearest metre?', 1,
 '[{"text": "27 m", "feedback": "This just adds the two given sides directly — since they meet at a 50° angle rather than forming a straight line, the cosine law is needed instead."}, {"text": "12 m", "feedback": "Correct. By the cosine law, third side² = 12²+15²−2(12)(15)cos(50°) ≈ 137.6, so the third side ≈ √137.6 ≈ 12 m."}, {"text": "19 m", "feedback": "This is too large — recheck the subtraction in third side² = 12²+15²−2(12)(15)cos(50°); the last term should reduce the sum of squares, since cos(50°) is positive."}, {"text": "3 m", "feedback": "This is too small for two sides of length 12 and 15 that only come together at a 50° angle — recheck the full cosine law expression before taking the square root."}]'::jsonb,
 'cosine-law-third-side-application'),
('MPM2D', 'trigonometry', 'cosine-law', 14, 'Medium',
 'In a triangle, a = 8, b = 11, and the angle between them, C = 60°. What is the length of side c, to one decimal place?', 1,
 '[{"text": "c ≈ 13.6", "feedback": "This is too large — recheck the subtraction step in c² = a²+b²−2ab·cos(C); the last term should reduce the sum of squares here."}, {"text": "c ≈ 9.8", "feedback": "Correct. By the cosine law, c² = 8²+11²−2(8)(11)cos(60°) = 185−88 = 97, so c ≈ √97 ≈ 9.8."}, {"text": "c ≈ 19.0", "feedback": "This adds the two given sides directly — the cosine law is needed since they meet at a 60° angle, not a straight line."}, {"text": "c ≈ 97.0", "feedback": "This is c², the value before the final square root — one more step is needed to find c itself."}]'::jsonb,
 'cosine-law-solve-for-side'),
('MPM2D', 'trigonometry', 'cosine-law', 15, 'Medium',
 'In a triangle, a = 9, c = 14, and the angle between them, B = 100°. What is the length of side b, to one decimal place?', 2,
 '[{"text": "b ≈ 16.6", "feedback": "Recheck the subtraction step in b² = a²+c²−2ac·cos(B); with B obtuse, cos(B) is negative, so this term actually adds to a²+c², making b larger than this."}, {"text": "b ≈ 5.0", "feedback": "This is far too small — recompute a²+c²−2ac·cos(100°) carefully, remembering that cos(100°) is negative."}, {"text": "b ≈ 17.9", "feedback": "Correct. By the cosine law, b² = 9²+14²−2(9)(14)cos(100°) = 277−252×cos(100°) ≈ 320.8, so b ≈ √320.8 ≈ 17.9."}, {"text": "b ≈ 23.0", "feedback": "This adds the two given sides directly — the cosine law is needed since they meet at a 100° angle, not a straight line."}]'::jsonb,
 'cosine-law-solve-for-side-obtuse'),
('MPM2D', 'trigonometry', 'cosine-law', 16, 'Medium',
 'In a triangle, b = 12, c = 15, and the angle between them, A = 70°. What is the length of side a, to one decimal place?', 3,
 '[{"text": "a ≈ 27.0", "feedback": "This adds the two given sides directly — the cosine law is needed since they meet at a 70° angle, not a straight line."}, {"text": "a ≈ 3.0", "feedback": "This is too small — recompute b²+c²−2bc·cos(70°) carefully before taking the square root."}, {"text": "a ≈ 369.0", "feedback": "This is a², the value before the final square root — one more step is needed to find a itself."}, {"text": "a ≈ 15.7", "feedback": "Correct. By the cosine law, a² = 12²+15²−2(12)(15)cos(70°) = 369−360×cos(70°) ≈ 245.9, so a ≈ √245.9 ≈ 15.7."}]'::jsonb,
 'cosine-law-solve-for-side'),
('MPM2D', 'trigonometry', 'cosine-law', 17, 'Medium',
 'In a triangle, a = 6, b = 9, and the angle between them, C = 120°. What is the length of side c, to one decimal place?', 1,
 '[{"text": "c ≈ 6.5", "feedback": "Recheck the sign: since C is obtuse, cos(120°) is negative, so the last term −2ab·cos(C) actually *adds* to a²+b², making c larger than a or b."}, {"text": "c ≈ 13.1", "feedback": "Correct. By the cosine law, c² = 6²+9²−2(6)(9)cos(120°) = 117−108×(−0.5) = 117+54 = 171, so c ≈ √171 ≈ 13.1."}, {"text": "c ≈ 15.0", "feedback": "This adds the two given sides directly — the cosine law is needed since they meet at a 120° angle, not a straight line."}, {"text": "c ≈ 3.0", "feedback": "This is far too small — recompute 6²+9²−2(6)(9)cos(120°) carefully."}]'::jsonb,
 'cosine-law-solve-for-side-obtuse'),
('MPM2D', 'trigonometry', 'cosine-law', 18, 'Medium',
 'A triangular sail has two sides of 4 m and 6 m, with an included angle of 65°. Find the length of the third side, to one decimal place.', 2,
 '[{"text": "10.0 m", "feedback": "This just adds the two given sides directly — the cosine law is needed since they meet at a 65° angle, not a straight line."}, {"text": "2.0 m", "feedback": "This subtracts the two given sides instead of using the full cosine law expression."}, {"text": "5.6 m", "feedback": "Correct. By the cosine law, third side² = 4²+6²−2(4)(6)cos(65°) ≈ 31.7, so the third side ≈ √31.7 ≈ 5.6 m."}, {"text": "31.7 m", "feedback": "This is the third side squared, the value before the final square root — one more step is needed."}]'::jsonb,
 'acute-triangle-cosine-law-application'),
('MPM2D', 'trigonometry', 'cosine-law', 19, 'Medium',
 'A triangular plot has two sides of 9 m and 13 m, with an included angle of 40°. Find the length of the third side, to one decimal place.', 1,
 '[{"text": "22.0 m", "feedback": "This just adds the two given sides directly — the cosine law is needed since they meet at a 40° angle, not a straight line."}, {"text": "8.4 m", "feedback": "Correct. By the cosine law, third side² = 9²+13²−2(9)(13)cos(40°) ≈ 70.7, so the third side ≈ √70.7 ≈ 8.4 m."}, {"text": "4.0 m", "feedback": "This subtracts the two given sides instead of using the full cosine law expression."}, {"text": "70.7 m", "feedback": "This is the third side squared, the value before the final square root — one more step is needed."}]'::jsonb,
 'acute-triangle-cosine-law-application'),
('MPM2D', 'trigonometry', 'cosine-law', 20, 'Medium',
 'In acute triangle DEF, angle D = 55°, side d = 18, and angle E = 65°. Find the length of side e, to one decimal place.', 3,
 '[{"text": "e ≈ 18.0", "feedback": "This just reuses side d — apply the sine law ratio to find the actual value of e."}, {"text": "e ≈ 15.4", "feedback": "This looks like sin(D) and sin(E) were swapped in the ratio — side e should come out larger than side d, since angle E is bigger than angle D."}, {"text": "e ≈ 22.4", "feedback": "This is too large — double check that sin(65°) and sin(55°) were placed correctly in the ratio."}, {"text": "e ≈ 19.9", "feedback": "Correct. By the sine law, d÷sin(D) = e÷sin(E), so e = 18 × sin(65°) ÷ sin(55°) ≈ 19.9."}]'::jsonb,
 'acute-triangle-sine-law-application'),
('MPM2D', 'trigonometry', 'cosine-law', 21, 'Medium',
 'In an acute triangle, two angles are 48° and 72°, and the side opposite the 48° angle is 10. Find the side opposite the third angle, to one decimal place.', 0,
 '[{"text": "11.7", "feedback": "Correct. The third angle is 180°−48°−72° = 60°. By the sine law, 10÷sin(48°) = x÷sin(60°), so x = 10 × sin(60°) ÷ sin(48°) ≈ 11.7."}, {"text": "10.0", "feedback": "This just reuses the given side — the third angle (60°) and the sine law are still needed to find its opposite side."}, {"text": "15.0", "feedback": "This doesn''t come from the sine law ratio — recompute the third angle (180°−48°−72°=60°) and apply 10×sin(60°)÷sin(48°)."}, {"text": "8.5", "feedback": "This looks like sin(48°) and sin(60°) were swapped in the ratio — the third side should come out larger than 10, since 60° is bigger than 48°."}]'::jsonb,
 'acute-triangle-sine-law-third-side'),
('MPM2D', 'trigonometry', 'cosine-law', 22, 'Medium',
 'In triangle ABC, b = 7, c = 9 and angle A = 60°. What is side a, to one decimal?', 1,
 '[
   {"text": "2.0 cm", "feedback": "Order of operations: only the 2bc multiplies cos A. That slip lands on a², and the square root has still to be taken."},
   {"text": "8.2 cm", "feedback": "Correct."},
   {"text": "67.0 cm", "feedback": "67 is a², the squared side. The square root finishes it."},
   {"text": "11.4 cm", "feedback": "The -2bc cos A term was dropped — that is Pythagoras, which needs a right angle."}
 ]'::jsonb,
 null),
('MPM2D', 'trigonometry', 'cosine-law', 23, 'Challenge',
 'A triangle has sides a = 8, b = 10, and c = 13. What is the measure of angle C, to the nearest degree?', 2,
 '[{"text": "C ≈ 47°", "feedback": "This is too small for the angle opposite the longest side — recheck the cosine law formula cos(C) = (a²+b²−c²)÷(2ab)."}, {"text": "C ≈ 66°", "feedback": "This doesn''t match cos⁻¹ of the correct ratio — recompute a²+b²−c² = 64+100−169 = −5 before dividing by 2ab."}, {"text": "C ≈ 92°", "feedback": "Correct. By the cosine law, cos(C) = (a²+b²−c²)÷(2ab) = (64+100−169)÷(2×8×10) = −5÷160 ≈ −0.031, so C ≈ cos⁻¹(−0.031) ≈ 92°."}, {"text": "C ≈ 128°", "feedback": "This is too large — the numerator (a²+b²−c²) comes out only slightly negative here, giving an angle just barely over 90°, not this much larger."}]'::jsonb,
 'cosine-law-solve-for-angle'),
('MPM2D', 'trigonometry', 'cosine-law', 24, 'Challenge',
 'A surveyor measures a triangular plot of land with sides 40 m, 55 m, and 65 m. What is its largest angle, to the nearest degree?', 3,
 '[{"text": "40°", "feedback": "The largest angle is opposite the longest side (65 m), not the shortest one (40 m) — use the cosine law with c = 65 to find it."}, {"text": "55°", "feedback": "This uses the wrong side as the one opposite the unknown angle — the largest angle sits opposite the longest side, 65 m, not 55 m."}, {"text": "65°", "feedback": "This just reuses one of the given side lengths as if it were the angle — apply the cosine law with the longest side (65) as c to actually find the angle."}, {"text": "85°", "feedback": "Correct. The largest angle is opposite the longest side (65). By the cosine law, cosθ = (40²+55²−65²)÷(2×40×55) ≈ 0.09, so θ ≈ cos⁻¹(0.09) ≈ 85°."}]'::jsonb,
 'largest-angle-opposite-longest-side'),
('MPM2D', 'trigonometry', 'cosine-law', 25, 'Challenge',
 'A triangle has sides a = 7, b = 9, and c = 11. What is the measure of angle C, to the nearest degree?', 1,
 '[{"text": "C ≈ 41°", "feedback": "This doesn''t match cos⁻¹ of the correct ratio — recompute a²+b²−c² = 49+81−121 = 9 before dividing by 2ab."}, {"text": "C ≈ 86°", "feedback": "Correct. By the cosine law, cos(C) = (a²+b²−c²)÷(2ab) = (49+81−121)÷(2×7×9) = 9÷126 ≈ 0.071, so C ≈ cos⁻¹(0.071) ≈ 86°."}, {"text": "C ≈ 94°", "feedback": "This is close, but recompute a²+b²−c² = 49+81−121 = 9 precisely, then divide by 2ab before taking the inverse cosine."}, {"text": "C ≈ 65°", "feedback": "This doesn''t match cos⁻¹ of the correct ratio — recheck the formula cos(C) = (a²+b²−c²)÷(2ab)."}]'::jsonb,
 'cosine-law-solve-for-angle'),
('MPM2D', 'trigonometry', 'cosine-law', 26, 'Challenge',
 'A triangle has sides a = 6, b = 8, and c = 11. What is the measure of the angle opposite side c, to the nearest degree?', 2,
 '[{"text": "48°", "feedback": "This doesn''t account for the negative value of a²+b²−c² — recompute 36+64−121 = −21 before dividing by 2ab."}, {"text": "77°", "feedback": "Recheck the cosine value: (36+64−121)÷(2×6×8) = −21÷96 ≈ −0.219 — this doesn''t match cos⁻¹ of that value."}, {"text": "103°", "feedback": "Correct. By the cosine law, cos(C) = (6²+8²−11²)÷(2×6×8) = (36+64−121)÷96 = −21÷96 ≈ −0.219, so C ≈ cos⁻¹(−0.219) ≈ 103° — a negative cosine value means this angle is obtuse."}, {"text": "13°", "feedback": "This is far too small — recheck that a²+b²−c² comes out negative here, which means the angle itself must be obtuse (greater than 90°)."}]'::jsonb,
 'cosine-law-solve-for-angle-obtuse'),
('MPM2D', 'trigonometry', 'cosine-law', 27, 'Challenge',
 'A triangle has sides a = 10, b = 12, and c = 15. What is the measure of the smallest angle (opposite the shortest side), to the nearest degree?', 0,
 '[{"text": "A ≈ 42°", "feedback": "Correct. The smallest angle is opposite the shortest side, a = 10. By the cosine law, cos(A) = (b²+c²−a²)÷(2bc) = (144+225−100)÷360 = 269÷360 ≈ 0.747, so A ≈ cos⁻¹(0.747) ≈ 42°."}, {"text": "B ≈ 42°, opposite side b", "feedback": "The smallest angle should be opposite the *shortest* side, which is a = 10, not b = 12."}, {"text": "A ≈ 65°", "feedback": "Recheck the ratio: cos(A) = (b²+c²−a²)÷(2bc) = 269÷360 — this doesn''t match cos⁻¹ of a value leading to 65°."}, {"text": "A ≈ 48°", "feedback": "Recompute 144+225−100 = 269 and divide by 2×12×15 = 360 before taking the inverse cosine."}]'::jsonb,
 'cosine-law-smallest-angle'),
('MPM2D', 'trigonometry', 'cosine-law', 28, 'Challenge',
 'A triangle has sides a = 5, b = 7, and c = 9. What is the measure of the largest angle (opposite the longest side), to the nearest degree?', 3,
 '[{"text": "C ≈ 84°", "feedback": "Recheck the sign: a²+b²−c² = 25+49−81 = −7, which is negative — that means the angle itself is obtuse, greater than 90°."}, {"text": "A ≈ 96°, opposite side a", "feedback": "The largest angle should be opposite the *longest* side, which is c = 9, not a = 5."}, {"text": "C ≈ 90°, since it''s a right triangle", "feedback": "Check whether a²+b² actually equals c²: 25+49 = 74, not 81 — this isn''t a right triangle."}, {"text": "C ≈ 96°", "feedback": "Correct. The largest angle is opposite the longest side, c = 9. By the cosine law, cos(C) = (a²+b²−c²)÷(2ab) = (25+49−81)÷70 = −7÷70 = −0.1, so C ≈ cos⁻¹(−0.1) ≈ 96°."}]'::jsonb,
 'cosine-law-largest-angle'),
('MPM2D', 'trigonometry', 'cosine-law', 29, 'Challenge',
 'A triangular garden has sides of 14 m and 18 m, with an included angle of 55°. Find its perimeter, to one decimal place.', 1,
 '[{"text": "47.0 m", "feedback": "This adds the two given sides plus a rounded guess for the third — recompute the third side using the full cosine law expression."}, {"text": "47.2 m", "feedback": "Correct. By the cosine law, the third side² = 14²+18²−2(14)(18)cos(55°) ≈ 230.9, so the third side ≈ 15.2 m; the perimeter is 14+18+15.2 ≈ 47.2 m."}, {"text": "32.0 m", "feedback": "This only adds the two given sides — the third side, found using the cosine law, still needs to be included."}, {"text": "64.2 m", "feedback": "This looks like the third side was added twice, or another arithmetic slip occurred — recompute 14+18+(third side) carefully."}]'::jsonb,
 'acute-triangle-perimeter-application'),
('MPM2D', 'trigonometry', 'cosine-law', 30, 'Challenge',
 'A triangle has sides 11, 13, and 16. Find its smallest angle, to the nearest degree.', 2,
 '[{"text": "53°", "feedback": "This doesn''t match cos⁻¹ of the correct ratio for the angle opposite the shortest side (11) — recheck the cosine law setup."}, {"text": "61°", "feedback": "Recheck which side is shortest — the smallest angle is opposite the shortest side, 11, not one of the other two."}, {"text": "43°", "feedback": "Correct. The smallest angle is opposite the shortest side, 11. By the cosine law, cos(A) = (13²+16²−11²)÷(2×13×16) = (169+256−121)÷416 = 304÷416 ≈ 0.731, so A ≈ cos⁻¹(0.731) ≈ 43°."}, {"text": "76°", "feedback": "This is too large for the angle opposite the shortest side — recheck the cosine law ratio (13²+16²−11²)÷(2×13×16)."}]'::jsonb,
 'acute-triangle-smallest-angle'),
('MPM2D', 'trigonometry', 'cosine-law', 31, 'Challenge',
 'In a triangle, a = 9, b = 12, and angle C = 48°. Find side c, then use it to find angle B (both to one decimal place / nearest degree).', 3,
 '[{"text": "c ≈ 21.0, B ≈ 34°", "feedback": "This adds the two given sides directly for c — the cosine law is needed since they meet at a 48° angle, not a straight line."}, {"text": "c ≈ 3.0, B ≈ 84°", "feedback": "The value of B is close, but recompute c using the full cosine law expression, c² = 9²+12²−2(9)(12)cos(48°), before taking the square root."}, {"text": "c ≈ 9.0, B ≈ 48°", "feedback": "This just reuses side a for c and angle C for B — both quantities need to be freshly computed using the cosine law and then the sine law."}, {"text": "c ≈ 9.0, B ≈ 84°", "feedback": "Correct. First, c² = 9²+12²−2(9)(12)cos(48°) ≈ 80.5, so c ≈ 9.0. Then by the sine law, sin(B) = 12×sin(48°)÷9.0 ≈ 0.994, giving B ≈ 84°."}]'::jsonb,
 'acute-triangle-cosine-then-sine'),
('MPM2D', 'trigonometry', 'cosine-law', 32, 'Challenge',
 'A triangle has sides of 10 and 14, with an included angle of 40°. Find its area, to one decimal place.', 0,
 '[{"text": "45.0", "feedback": "Correct. Area = ½ × 10 × 14 × sin(40°) ≈ 45.0."}, {"text": "70.0", "feedback": "This is ½ × 10 × 14 without the sine of the included angle — the angle between the two sides still needs to be factored in."}, {"text": "140.0", "feedback": "This multiplies the two sides without the ½ factor or the sine of the included angle."}, {"text": "107.1", "feedback": "This uses cos(40°) instead of sin(40°) — the area formula for two sides and an included angle uses sine, not cosine."}]'::jsonb,
 'acute-triangle-area-formula'),
('MPM2D', 'trigonometry', 'cosine-law', 33, 'Challenge',
 'A triangle has sides 5, 7 and 10. What is the angle opposite the 10 side, to one decimal?', 3,
 '[
   {"text": "138.0°", "feedback": "The denominator is 2ab — two times 5 times 7. The 2 was dropped."},
   {"text": "68.2°", "feedback": "The sign was dropped: 25 + 49 - 100 is NEGATIVE 26, and the minus is what makes the angle obtuse."},
   {"text": "27.7°", "feedback": "The side OPPOSITE the wanted angle goes in the subtracted spot: 10² is subtracted, not 5²."},
   {"text": "111.8°", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'trigonometry', 'cosine-law', 34, 'Challenge',
 'In triangle ABC, b = 6, c = 8 and angle A = 120°. What is side a, to one decimal?', 2,
 '[
   {"text": "7.2", "feedback": "cos 120° is NEGATIVE 0.5, so the correction term flips to PLUS 48. Using +0.5 shrinks the side."},
   {"text": "10.0", "feedback": "The cosine term was dropped. Pythagoras only survives at exactly 90°."},
   {"text": "12.2", "feedback": "Correct."},
   {"text": "148.0", "feedback": "148 is a squared. Root it."}
 ]'::jsonb,
 null),
('MPM2D', 'trigonometry', 'cosine-law', 35, 'Challenge',
 'A triangle has two known sides and the angle BETWEEN them, no right angle. Which tool finds the third side?', 0,
 '[
   {"text": "The cosine law", "feedback": "Correct."},
   {"text": "The Pythagorean theorem", "feedback": "Pythagoras is the 90° special case of a more general rule — its correction term has been deleted."},
   {"text": "The sine law", "feedback": "The sine law needs a side paired with its OPPOSITE angle — the contained angle breaks that pairing."},
   {"text": "SOH CAH TOA", "feedback": "The primary ratios need a right angle, and this triangle has none."}
 ]'::jsonb,
 null),
('MPM2D', 'trigonometry', 'cosine-law', 36, 'Advanced',
 'Two ships leave port at the same time. One sails 20 km due north; the other sails 15 km along a path that makes a 110° angle with the first ship''s path. How far apart are the ships, to the nearest km?', 1,
 '[{"text": "35 km", "feedback": "This just adds the two distances directly — since the ships aren''t travelling in the same straight line, the cosine law is needed instead of simple addition."}, {"text": "29 km", "feedback": "Correct. By the cosine law, distance² = 20²+15²−2(20)(15)cos(110°) ≈ 830, so distance ≈ √830 ≈ 29 km."}, {"text": "18 km", "feedback": "This is too small for two paths that diverge by an obtuse angle (110°) — recheck the sign on the cos(110°) term, since cosine is negative for angles over 90°."}, {"text": "25 km", "feedback": "This looks like it used the Pythagorean theorem (assuming a 90° angle) instead of the cosine law — but the angle between the paths here is 110°, not 90°."}]'::jsonb,
 'cosine-law-navigation-application'),
('MPM2D', 'trigonometry', 'cosine-law', 37, 'Advanced',
 'In triangle ABC, a = 14, b = 18, and angle C = 40°. Find angle A, to the nearest degree.', 0,
 '[{"text": "A ≈ 51°", "feedback": "Correct. First use the cosine law to find c: c² = 14²+18²−2(14)(18)cos(40°) ≈ 134, so c ≈ 11.6. Then the sine law gives sin(A) = 14×sin(40°)÷11.6 ≈ 0.777, so A ≈ 51°."}, {"text": "A ≈ 40°", "feedback": "This just reuses the given angle C — since sides a and b differ, angles A and C must differ too; side c needs to be found first via the cosine law."}, {"text": "A ≈ 65°", "feedback": "This is too large — recompute side c with the cosine law first (c ≈ 11.6), then use it correctly as the denominator in the sine law ratio for angle A."}, {"text": "A ≈ 89°", "feedback": "This would require side c to come out much shorter than it actually does — recheck the cosine law calculation for c before applying the sine law."}]'::jsonb,
 'cosine-then-sine-law-two-step'),
('MPM2D', 'trigonometry', 'cosine-law', 38, 'Advanced',
 'Two hikers leave camp together, one walking 8 km on one path, the other walking 11 km on a path that makes a 75° angle with the first. How far apart are they, to one decimal place?', 2,
 '[{"text": "19.0 km", "feedback": "This just adds the two distances directly — since the two paths diverge at a 75° angle rather than continuing in a straight line, the cosine law is needed."}, {"text": "9.6 km", "feedback": "This is too small for two paths diverging at 75° — recheck the full cosine law expression before taking the square root."}, {"text": "11.8 km", "feedback": "Correct. By the cosine law, distance² = 8²+11²−2(8)(11)cos(75°) ≈ 139.4, so distance ≈ √139.4 ≈ 11.8 km."}, {"text": "13.4 km", "feedback": "This looks like the angle was treated as obtuse (using a negative cosine) — but 75° is acute, so cos(75°) is positive here."}]'::jsonb,
 'cosine-law-navigation-application'),
('MPM2D', 'trigonometry', 'cosine-law', 39, 'Advanced',
 'A triangular park has two sides of length 120 m and 150 m, with an included angle of 100°. Find the length of the third side, to the nearest metre.', 1,
 '[{"text": "270 m", "feedback": "This just adds the two given sides directly — the cosine law is needed since they meet at a 100° angle, not a straight line."}, {"text": "208 m", "feedback": "Correct. By the cosine law, third side² = 120²+150²−2(120)(150)cos(100°) ≈ 43,151, so the third side ≈ √43,151 ≈ 208 m."}, {"text": "184 m", "feedback": "This looks like the angle 100° was treated as acute (using a positive cosine) — but 100° is obtuse, so cos(100°) is actually negative."}, {"text": "30 m", "feedback": "This subtracts the two given sides instead of using the full cosine law expression."}]'::jsonb,
 'cosine-law-application'),
('MPM2D', 'trigonometry', 'cosine-law', 40, 'Advanced',
 'A surveyor measures a triangular lot with sides 45 m, 60 m, and 75 m. What is the largest angle, to the nearest degree?', 3,
 '[{"text": "It cannot be a right angle, since 45-60-75 aren''t a Pythagorean triple", "feedback": "Check this carefully: 45² + 60² = 2025+3600 = 5625, and 75² = 5625 — these are actually equal, meaning it IS a right angle."}, {"text": "85°, opposite the side of 60 m", "feedback": "The largest angle is opposite the *longest* side (75 m), not the side of 60 m — and its actual measure comes out to a round number."}, {"text": "The angle can''t be determined without more information", "feedback": "The three side lengths (SSS) are exactly enough information to find any angle in a triangle, using the cosine law."}, {"text": "90°, opposite the side of 75 m", "feedback": "Correct. The largest angle is opposite the longest side (75 m). Checking: 45²+60² = 2025+3600 = 5625 = 75², so this is a right triangle (a 3-4-5 triangle scaled by 15), and the angle opposite 75 m is exactly 90°."}]'::jsonb,
 'cosine-law-recognize-right-triangle'),
('MPM2D', 'trigonometry', 'cosine-law', 41, 'Advanced',
 'In triangle ABC, a = 10, b = 14, and angle C = 50°. Find side c, then use it to find angle A, both to one decimal place / nearest degree.', 0,
 '[{"text": "c ≈ 10.8, A ≈ 45°", "feedback": "Correct. First, c² = 10²+14²−2(10)(14)cos(50°) ≈ 116, so c ≈ 10.8. Then by the sine law, sin(A) = 10×sin(50°)÷10.8 ≈ 0.709, giving A ≈ 45°."}, {"text": "c ≈ 4.0, A ≈ 45°", "feedback": "The value of A is right, but recompute c using the full cosine law expression, c² = 10²+14²−2(10)(14)cos(50°), before taking the square root."}, {"text": "c ≈ 10.8, A ≈ 65°", "feedback": "The value of c is right, but recheck the sine law step: sin(A) = a×sin(C)÷c, using the correct value of c you just found."}, {"text": "c ≈ 24.0, A ≈ 25°", "feedback": "This adds the two given sides directly for c — the cosine law is needed since they meet at a 50° angle, not a straight line."}]'::jsonb,
 'cosine-then-sine-law-two-step'),
('MPM2D', 'trigonometry', 'cosine-law', 42, 'Advanced',
 'In a triangle, a = 20, b = 25, and angle C = 35°. Find side c, then use it to find angle B (both to one decimal place / nearest degree).', 2,
 '[{"text": "c ≈ 45.0, B ≈ 35°", "feedback": "This adds the two given sides directly for c — the cosine law is needed since they meet at a 35° angle, not a straight line."}, {"text": "c ≈ 5.0, B ≈ 88°", "feedback": "The value of B is close, but recompute c using the full cosine law expression, c² = 20²+25²−2(20)(25)cos(35°), before taking the square root."}, {"text": "c ≈ 14.3, B ≈ 88°", "feedback": "Correct. First, c² = 20²+25²−2(20)(25)cos(35°) ≈ 205.8, so c ≈ 14.3. Then by the sine law, sin(B) = 25×sin(35°)÷14.3 ≈ 0.9997, giving B ≈ 88°."}, {"text": "c ≈ 14.3, B ≈ 35°", "feedback": "This just reuses angle C''s value for B — angle B still needs to be freshly computed using the sine law with the newly-found side c."}]'::jsonb,
 'acute-triangle-cosine-then-sine'),
('MPM2D', 'trigonometry', 'cosine-law', 43, 'Advanced',
 'A triangle has sides a = 15 and b = 20, and its area is 120. Find the acute angle C between them, to the nearest degree.', 1,
 '[{"text": "C ≈ 37°", "feedback": "This doesn''t match sin⁻¹ of the correct ratio — recompute sin(C) = (2×Area)÷(a×b) = 240÷300 first."}, {"text": "C ≈ 53°", "feedback": "Correct. Using Area = ½ab·sin(C), 120 = ½(15)(20)sin(C) gives sin(C) = 240÷300 = 0.8, so C = sin⁻¹(0.8) ≈ 53° (taking the acute solution)."}, {"text": "C ≈ 80°", "feedback": "This is too large — recompute sin(C) = (2×120)÷(15×20) = 0.8, then take the inverse sine for the acute angle."}, {"text": "C ≈ 127°", "feedback": "This is the obtuse solution to sin(C) = 0.8 — since the triangle is described as acute, take the acute angle instead, sin⁻¹(0.8) ≈ 53°."}]'::jsonb,
 'acute-triangle-area-solve-for-angle'),
('MPM2D', 'trigonometry', 'cosine-law', 44, 'Advanced',
 'A triangle has two sides of 12 and 16, with an included angle of 55°. Find both its area and its perimeter, each to one decimal place.', 3,
 '[{"text": "Area ≈ 78.6, perimeter ≈ 28.0", "feedback": "The area is right, but the perimeter is missing the third side — find it using the cosine law before adding it to 12+16."}, {"text": "Area ≈ 96.0, perimeter ≈ 41.4", "feedback": "Recompute the area using ½ × 12 × 16 × sin(55°), not simply ½ × 12 × 16 without the sine factor."}, {"text": "Area ≈ 78.6, perimeter ≈ 40.0", "feedback": "The area is right, but recompute the third side using the cosine law more precisely before adding it to 12+16."}, {"text": "Area ≈ 78.6, perimeter ≈ 41.4", "feedback": "Correct. Area = ½(12)(16)sin(55°) ≈ 78.6; the third side is √(12²+16²−2(12)(16)cos(55°)) ≈ 13.4, so the perimeter is 12+16+13.4 ≈ 41.4."}]'::jsonb,
 'acute-triangle-area-and-perimeter'),
('MPM2D', 'trigonometry', 'cosine-law', 45, 'Advanced',
 'A triangle has two sides of 13 and 18, with an included angle of 62° between them. Find the height measured from the vertex opposite the 18 m side, to one decimal place.', 0,
 '[{"text": "11.5 m", "feedback": "Correct. The height from the vertex between the 13 m side and the 62° angle, measured perpendicular to the 18 m side, is 13×sin(62°) ≈ 11.5 m."}, {"text": "15.9 m", "feedback": "This uses cos(62°) instead of sin(62°) — the height perpendicular to the base uses the sine of the angle at the vertex."}, {"text": "18.0 m", "feedback": "This just reuses the base length — the height is a separate perpendicular measurement, found using 13×sin(62°)."}, {"text": "6.1 m", "feedback": "This looks like a different combination of the given values — recompute 13×sin(62°) directly."}]'::jsonb,
 'acute-triangle-height-application'),
('MPM2D', 'trigonometry', 'cosine-law', 46, 'Advanced',
 'A triangle has sides 8, 11 and 15. What is its SMALLEST angle, to one decimal?', 2,
 '[
   {"text": "31.8°", "feedback": "That rounds the cosine ratio to two decimals before taking the inverse. Round only at the end."},
   {"text": "45.6°", "feedback": "That angle faces the 11. Opposite the 8 means the 8² is the subtracted square."},
   {"text": "31.3°", "feedback": "Correct."},
   {"text": "103.1°", "feedback": "That is the angle opposite the 15 — the LARGEST angle. The smallest faces the shortest side, 8."}
 ]'::jsonb,
 null),
('MPM2D', 'trigonometry', 'cosine-law', 47, 'Advanced',
 'Two roads leave a town at 50° to each other. Cars drive 40 km down one and 65 km down the other. How far apart are they, to one decimal?', 2,
 '[
   {"text": "76.3 km", "feedback": "That is Pythagoras, which needs 90° between the roads. At 50° the cosine term stays."},
   {"text": "20.0 km", "feedback": "Order of operations: cos 50° multiplies ONLY the 2ab term. Applying it to the whole bracket is the classic cosine law slip."},
   {"text": "49.8 km", "feedback": "Correct."},
   {"text": "105.0 km", "feedback": "40 + 65 lays the roads end to end. They fan out at an angle, so the gap is shorter."}
 ]'::jsonb,
 null),
('MPM2D', 'trigonometry', 'cosine-law', 48, 'Advanced',
 'A triangle has sides 6, 6 and 10. What is the angle between the two equal sides, to one decimal?', 1,
 '[
   {"text": "146.4°", "feedback": "That is the supplement of a base angle. The apex is not what is left when a base angle is taken from 180."},
   {"text": "112.9°", "feedback": "Correct."},
   {"text": "33.6°", "feedback": "That is a BASE angle, opposite one of the 6 sides. The apex angle faces the 10."},
   {"text": "60.0°", "feedback": "Equal sides do not force 60° — that needs all THREE sides equal."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'common-factoring', 1, 'Easy',
 'What is the greatest common factor of 12x³ and 18x²?', 3,
 '[
   {"text": "2x", "feedback": "2 divides both but is not the GREATEST number that does. 6 is."},
   {"text": "6x³", "feedback": "The variable part takes the LOWEST power the terms share. 12x³ has x³ but 18x² does not."},
   {"text": "36x²", "feedback": "36 is a common MULTIPLE of 12 and 18. The greatest common factor of them is 6."},
   {"text": "6x²", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'common-factoring', 2, 'Easy',
 'Factor: 5x + 20', 2,
 '[
   {"text": "x(5 + 20)", "feedback": "x is not a factor of the plain number 20. Only the 5 is common to both terms."},
   {"text": "5(x + 15)", "feedback": "That takes 5 away from the 20 instead of dividing it by the common factor."},
   {"text": "5(x + 4)", "feedback": "Correct."},
   {"text": "5(x + 20)", "feedback": "After removing the 5, the 20 divides by it too: 20 over 5 is 4."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'common-factoring', 3, 'Easy',
 'Factor completely: 8x² - 6x', 3,
 '[
   {"text": "2(4x² - 3x)", "feedback": "An x is still common inside the brackets. The greatest common factor includes it."},
   {"text": "2x(4x - 6)", "feedback": "The 6x divides by the FULL common factor 2x, leaving 3, not 6."},
   {"text": "x(8x - 6)", "feedback": "The 2 is still common inside. Take out the greatest common factor, 2x, in one step."},
   {"text": "2x(4x - 3)", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'common-factoring', 4, 'Medium',
 'Factor completely: 21x³y² - 28x²y⁴ + 7x²y²', 1,
 '[
   {"text": "7x²y²(3x - 4y²)", "feedback": "Removing the factor from the LAST term leaves 1, which must stay in the brackets — three terms in, three out."},
   {"text": "7x²y²(3x - 4y² + 1)", "feedback": "Correct."},
   {"text": "7x²y²(3x + 4y² + 1)", "feedback": "The common factor comes out positive, so the sign in front of each term is unchanged. The middle term is still subtracted."},
   {"text": "7xy(3x²y - 4xy³ + xy)", "feedback": "A bigger factor is available: every term carries x² and y², not just x and y."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'common-factoring', 5, 'Challenge',
 'Factor completely: 16x² + 26x - 12', 0,
 '[
   {"text": "2(8x - 3)(x + 2)", "feedback": "Correct."},
   {"text": "2(4x - 1)(2x + 6)", "feedback": "Another 2 still hides in (2x + 6), and the middle term does not check out."},
   {"text": "2(8x + 3)(x - 2)", "feedback": "Expand: the middle term becomes -13x, doubled -26x. The signs are reversed."},
   {"text": "(8x - 3)(2x + 4)", "feedback": "The common factor 2 belongs OUT FRONT, not inside (2x + 4)."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'common-factoring', 6, 'Challenge',
 'Factor completely: 3x³ - 27x', 0,
 '[
   {"text": "3x(x - 3)(x + 3)", "feedback": "Correct."},
   {"text": "3x(x² - 9)", "feedback": "x² - 9 is a difference of squares and factors further. Completely means all the way."},
   {"text": "3x(x - 3)²", "feedback": "(x - 3)² expands with a middle term -6x. The bracket x² - 9 needs (x - 3)(x + 3)."},
   {"text": "3(x³ - 9x)", "feedback": "An x is still common inside. Remove 3x, then factor what remains."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'common-factoring', 7, 'Advanced',
 'Factor completely: 2x⁴ - 32', 2,
 '[
   {"text": "2(x² - 4)(x² + 4)", "feedback": "One more step remains: x² - 4 splits into (x - 2)(x + 2)."},
   {"text": "(2x² - 8)(x² + 4)", "feedback": "A 2 is trapped inside the first bracket. Common factor out front first."},
   {"text": "2(x² + 4)(x - 2)(x + 2)", "feedback": "Correct."},
   {"text": "2(x⁴ - 16)", "feedback": "x⁴ - 16 keeps factoring: it is a difference of squares twice over."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'common-factoring', 8, 'Advanced',
 'Factor completely: 12x² - 27', 2,
 '[
   {"text": "3(2x - 3)²", "feedback": "That square has a middle term -36x when expanded times 3. No middle term exists here."},
   {"text": "(6x - 9)(2x + 3)", "feedback": "A common factor of 3 is trapped in the first bracket. Take out the 3 before the squares pattern."},
   {"text": "3(2x - 3)(2x + 3)", "feedback": "Correct."},
   {"text": "3(4x² - 9)", "feedback": "4x² - 9 is a difference of squares and splits further."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'factoring-ax-bx-c', 1, 'Easy',
 'To factor x² + 7x + 12, what two numbers are needed?', 1,
 '[
   {"text": "Numbers that add to 12 and multiply to give 7", "feedback": "The roles are swapped: the middle coefficient is the SUM, the constant is the PRODUCT."},
   {"text": "Numbers that add to 7 and multiply to 12", "feedback": "Correct."},
   {"text": "Numbers that subtract to 7 and divide to 12", "feedback": "The pattern from expanding (x + m)(x + n) is add and multiply."},
   {"text": "Numbers that both divide 7 without a remainder", "feedback": "7 is prime — this rule would find nothing. The pair works with 7 and 12 together."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'factoring-ax-bx-c', 2, 'Medium',
 'To factor 3x² + 10x + 8 by decomposition, the middle term splits using two numbers with what properties?', 0,
 '[
   {"text": "Sum 10 and product 24", "feedback": "Correct."},
   {"text": "Sum 13 and product 24", "feedback": "The 3 does not join the sum. It only enters through the product a times c."},
   {"text": "Sum 8 and product 30", "feedback": "The sum matches the MIDDLE coefficient, 10. The product uses 3 times 8."},
   {"text": "Sum 10 and product 8", "feedback": "The product target is a times c — 3 times 8 — once the leading coefficient is not 1."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'factoring-ax-bx-c', 3, 'Medium',
 'Factor: 3x² + 10x + 8', 1,
 '[
   {"text": "(x + 4)(x + 6)", "feedback": "The leading term must be 3x², so one factor carries the 3x."},
   {"text": "(3x + 4)(x + 2)", "feedback": "Correct."},
   {"text": "(3x + 2)(x + 4)", "feedback": "Check the middle term: 12x + 2x gives 14x, not 10x. Expand to verify."},
   {"text": "(3x + 8)(x + 1)", "feedback": "That expands to a middle term of 11x. The split 6x + 4x is the one that groups."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'factoring-ax-bx-c', 4, 'Medium',
 'Factor: 2x² - 7x + 6', 2,
 '[
   {"text": "(2x - 6)(x - 1)", "feedback": "A common factor of 2 hides in (2x - 6) that the original does not have. Expand and compare."},
   {"text": "(2x - 1)(x - 6)", "feedback": "That gives a middle term of -13x. The split of -7x is -3x and -4x."},
   {"text": "(2x - 3)(x - 2)", "feedback": "Correct."},
   {"text": "(2x + 3)(x + 2)", "feedback": "A positive constant with a NEGATIVE middle term needs both signs negative."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'factoring-ax-bx-c', 5, 'Challenge',
 'Factor completely: 6x² + 14x + 4', 3,
 '[
   {"text": "(6x + 2)(x + 2)", "feedback": "The middle term is right, but this is not finished: a whole number still divides through one of the brackets. Look for a common factor before splitting the trinomial."},
   {"text": "2(3x + 2)(x + 1)", "feedback": "Expand the brackets: the middle term becomes 5x, and doubled that is 10x, not 14x."},
   {"text": "(3x + 1)(2x + 4)", "feedback": "The x-terms are right, but a whole number still divides one of these brackets. Completely factored means nothing is left that can be taken out."},
   {"text": "2(3x + 1)(x + 2)", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'factoring-ax-bx-c', 6, 'Challenge',
 'Factor: 6x² + 13x - 5', 3,
 '[
   {"text": "(3x - 5)(2x + 1)", "feedback": "Check: 3x - 10x gives -7x, not 13x. Try grouping 6x² + 15x - 2x - 5."},
   {"text": "(3x + 1)(2x - 5)", "feedback": "Expand: the middle term comes out as -13x. The signs are on the wrong factors."},
   {"text": "(6x - 1)(x + 5)", "feedback": "That gives a middle term of 29x. The split of 13x is 15x - 2x."},
   {"text": "(3x - 1)(2x + 5)", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'factoring-ax-bx-c', 7, 'Challenge',
 'Factor: 4x² - 5xy - 6y²', 1,
 '[
   {"text": "(4x + 6y)(x - y)", "feedback": "6y and -y do give -6y², but the outer and inner products then add to +2xy, and a factor of 2 is trapped in the first bracket."},
   {"text": "(4x + 3y)(x - 2y)", "feedback": "Correct."},
   {"text": "(4x - 6y)(x + y)", "feedback": "A common factor of 2 is trapped in the first bracket, and the product of the outside terms is wrong."},
   {"text": "(4x - 3y)(x + 2y)", "feedback": "The middle term expands to +5xy with these signs. Flip them."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'factoring-ax-bx-c', 8, 'Advanced',
 'Factor by grouping: x³ + 3x² + 2x + 6', 1,
 '[
   {"text": "(x² + 3)(x + 2)", "feedback": "Expand it: the middle terms come out as 2x² + 3x, which is not what the polynomial shows."},
   {"text": "(x² + 2)(x + 3)", "feedback": "Correct."},
   {"text": "(x + 1)(x + 2)(x + 3)", "feedback": "Expanding that gives x³ + 6x² + 11x + 6. The x² coefficient here is 3."},
   {"text": "(x² + 2x)(x + 3)", "feedback": "x² + 2x still holds a common x. The first group contributes x² only, the second the 2."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'factoring-ax-bx-c', 9, 'Advanced',
 'Which product expands to 6x² - 7x - 20?', 0,
 '[
   {"text": "(3x + 4)(2x - 5)", "feedback": "Correct."},
   {"text": "(6x + 5)(x - 4)", "feedback": "That expands to a middle term of -19x. Split -7x as -15x + 8x and group."},
   {"text": "(3x - 5)(2x + 4)", "feedback": "A common factor of 2 hides in (2x + 4), and 6x² - 7x - 20 has none."},
   {"text": "(3x - 4)(2x + 5)", "feedback": "The middle term of that one is +7x. The signs sit on the wrong brackets."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'factoring-ax-bx-c', 10, 'Advanced',
 'Factor completely: x² y - 4y + x²z - 4z', 3,
 '[
   {"text": "(x² + 4)(y - z)", "feedback": "Group as y(x² - 4) + z(x² - 4): the shared bracket is x² MINUS 4, and (y + z) collects."},
   {"text": "x²(y + z) - 4(y + z)", "feedback": "That is the grouping STEP, not the factored result. Pull out the common bracket."},
   {"text": "(x² - 4)(y + z)", "feedback": "x² - 4 keeps factoring — the difference of squares is still whole."},
   {"text": "(x - 2)(x + 2)(y + z)", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'special-products', 1, 'Easy',
 'Which expression is a difference of squares?', 2,
 '[
   {"text": "x² + 49", "feedback": "A SUM of squares does not factor over the integers. The pattern needs a subtraction."},
   {"text": "x³ - 49", "feedback": "The powers must be squares too — x³ is not one."},
   {"text": "x² - 49", "feedback": "Correct."},
   {"text": "x² - 48", "feedback": "48 is not a perfect square. Both terms must be squares."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'special-products', 2, 'Easy',
 'Factor: x² - 49', 0,
 '[
   {"text": "(x - 7)(x + 7)", "feedback": "Correct."},
   {"text": "(x - 7)(x - 7)", "feedback": "Both signs negative gives +49 at the end, not -49. The signs must differ."},
   {"text": "(x + 7)(x + 7)", "feedback": "Two positive signs give +49 at the end and a middle term of +14x. A difference of squares has NO middle term."},
   {"text": "(x - 49)(x + 1)", "feedback": "Those multiply to x² - 48x - 49. Take the square root of each term instead: x and 7."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'special-products', 3, 'Medium',
 'Expand: (x + 4)²', 3,
 '[
   {"text": "x² + 16", "feedback": "Squaring a binomial produces a middle term: 2 times x times 4. The square does not distribute onto each term."},
   {"text": "x² + 8x + 8", "feedback": "The last term is 4 squared, which is 16."},
   {"text": "x² + 4x + 16", "feedback": "The middle term is TWICE the product of x and 4."},
   {"text": "x² + 8x + 16", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'special-products', 4, 'Medium',
 'Factor: 9x² - 25', 1,
 '[
   {"text": "(3x - 25)(3x + 1)", "feedback": "A difference of squares splits into root minus root and root plus root: 3x and 5."},
   {"text": "(3x - 5)(3x + 5)", "feedback": "Correct."},
   {"text": "(9x - 25)(9x + 25)", "feedback": "The square roots of the terms go in the brackets: √(9x²) is 3x, not 9x."},
   {"text": "(3x - 5)²", "feedback": "A square produces a middle term -30x. This expression has no middle term."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'special-products', 5, 'Medium',
 'Factor: x² + 12x + 36', 2,
 '[
   {"text": "(x + 6)(x - 6)", "feedback": "That is the pattern for x² MINUS 36. Here the middle term +12x signals a perfect square."},
   {"text": "(x + 4)(x + 9)", "feedback": "4 and 9 multiply to 36 but add to 13, not 12, so this pair misses the middle term."},
   {"text": "(x + 6)²", "feedback": "Correct."},
   {"text": "(x + 12)(x + 3)", "feedback": "Check the product: 12 times 3 is 36, but the sum is 15, not 12."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'special-products', 6, 'Challenge',
 'Factor: 25x² - 30x + 9', 1,
 '[
   {"text": "(5x - 3)(5x + 3)", "feedback": "That pattern is for 25x² - 9 with NO middle term. Here -30x is exactly twice 5x times 3."},
   {"text": "(5x - 3)²", "feedback": "Correct."},
   {"text": "(25x - 9)(x - 1)", "feedback": "Perfect square trinomials factor from the roots of the outer terms: 5x and 3."},
   {"text": "(5x + 3)²", "feedback": "The middle term of that square is +30x. The -30x needs the negative version."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'special-products', 7, 'Challenge',
 'Expand: (3x - 2y)²', 3,
 '[
   {"text": "9x² - 6xy + 4y²", "feedback": "The middle term DOUBLES the product of 3x and 2y: 12xy, not 6xy."},
   {"text": "9x² - 12xy - 4y²", "feedback": "The last term is (-2y) squared, and a square is positive."},
   {"text": "9x² + 12xy + 4y²", "feedback": "The middle term keeps the minus: 2 times 3x times -2y is negative."},
   {"text": "9x² - 12xy + 4y²", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'special-products', 8, 'Advanced',
 'Factor completely: x⁴ - 16', 2,
 '[
   {"text": "(x - 2)²(x + 2)²", "feedback": "That expands to (x² - 4)², which is x⁴ - 8x² + 16 — a middle term this expression does not have."},
   {"text": "(x² - 8)(x² + 2)", "feedback": "The square roots of x⁴ and 16 are x² and 4. Start from (x² - 4)(x² + 4)."},
   {"text": "(x² + 4)(x - 2)(x + 2)", "feedback": "Correct."},
   {"text": "(x² - 4)(x² + 4)", "feedback": "x² - 4 is itself a difference of squares and splits again. Completely means twice here."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'special-products', 9, 'Advanced',
 'The area of a square is 4x² + 12x + 9. What is its side length?', 3,
 '[
   {"text": "2x² + 3", "feedback": "Rooting 4x² halves the EXPONENT: it gives 2x, not 2x²."},
   {"text": "4x + 9", "feedback": "The side is the square ROOT of the area, and the root of 4x² is 2x."},
   {"text": "2x + 9", "feedback": "The last term of the side is the root of 9, which is 3. Check: the middle term 12x is 2 times 2x times 3."},
   {"text": "2x + 3", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'factoring', 'special-products', 10, 'Advanced',
 'x² - y² = 40 and x - y = 4. What is x + y?', 2,
 '[
   {"text": "4", "feedback": "4 is x - y, which the question gave. The other bracket is what it asks for."},
   {"text": "160", "feedback": "That multiplies the two givens. The factored form says 40 is already a PRODUCT of the two brackets."},
   {"text": "10", "feedback": "Correct."},
   {"text": "36", "feedback": "x² - y² FACTORS as (x - y)(x + y) — nothing subtracts from the 40."}
 ]'::jsonb,
 null),
('MPM2D', 'solving-quadratic-equations', 'solving-by-completing-the-square', 1, 'Easy',
 'Solve: (x + 4)² = 25', 1,
 '[
   {"text": "x = 21", "feedback": "25 - 4 subtracts before rooting. Square root the 25 first, then move the 4."},
   {"text": "x = 1 and x = -9", "feedback": "Correct."},
   {"text": "x = 5 and x = -5", "feedback": "That solves the bracket ITSELF equal to root 25. Finish by subtracting the 4 from each."},
   {"text": "x = 1 only", "feedback": "The root of 25 is plus OR minus 5, giving two answers."}
 ]'::jsonb,
 null),
('MPM2D', 'solving-quadratic-equations', 'solving-by-completing-the-square', 2, 'Medium',
 'Solve by completing the square: x² + 6x + 2 = 0', 2,
 '[
   {"text": "x = -3 + √7 only", "feedback": "The square root carries both signs — two solutions."},
   {"text": "x = -3 + √11 and x = -3 - √11", "feedback": "Moving the 2 across SUBTRACTS it from the completing constant — it was added instead."},
   {"text": "x = -3 + √7 and x = -3 - √7", "feedback": "Correct."},
   {"text": "x = 3 + √7 and x = 3 - √7", "feedback": "That reads the roots off the completed square with the 3 left as it stands."}
 ]'::jsonb,
 null),
('MPM2D', 'solving-quadratic-equations', 'solving-by-completing-the-square', 3, 'Medium',
 'Solve: (x - 2)² = 18. Give exact answers.', 1,
 '[
   {"text": "x = 2 + 3√2 only", "feedback": "Both signs of the root give solutions."},
   {"text": "x = 2 + 3√2 and x = 2 - 3√2", "feedback": "Correct."},
   {"text": "x = -2 + 3√2 and x = -2 - 3√2", "feedback": "The -2 in the bracket crosses over as +2."},
   {"text": "x = 2 + 9 and x = 2 - 9", "feedback": "√18 is not 9 — that halves instead of rooting. Simplify √18 by pulling out its perfect square factor."}
 ]'::jsonb,
 null),
('MPM2D', 'solving-quadratic-equations', 'solving-by-completing-the-square', 4, 'Challenge',
 'Solve by completing the square: 2x² - 12x + 10 = 0', 3,
 '[
   {"text": "x = 1 as the only solution", "feedback": "The square root carries both signs, so one of the two solutions has been dropped."},
   {"text": "x = 3 + √14 and x = 3 - √14", "feedback": "That adds the constant instead of subtracting it while completing the square. Watch the sign as the constant crosses the equals sign."},
   {"text": "x = -1 and x = -5", "feedback": "After dividing by 2, (x - 3)² = 4 unwinds around POSITIVE 3."},
   {"text": "x = 1 and x = 5", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'solving-quadratic-equations', 'solving-by-completing-the-square', 5, 'Advanced',
 'Two positive numbers differ by 6 and multiply to 91. What is the smaller one?', 3,
 '[
   {"text": "6", "feedback": "6 is the gap between them, given, not a value."},
   {"text": "91/6", "feedback": "The product does not divide by the difference. Set up n(n + 6) = 91 and factor."},
   {"text": "13", "feedback": "13 is the LARGER of the two numbers. The question asks for the smaller one."},
   {"text": "7", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'solving-quadratic-equations', 'standard-form-analysis', 1, 'Easy',
 'For y = x² - 6x + 2, the x-coordinate of the vertex is found by which calculation?', 0,
 '[
   {"text": "x = -b over 2a, giving 3", "feedback": "Correct."},
   {"text": "x = c over a, giving 2", "feedback": "c places the y-intercept, not the vertex."},
   {"text": "x = b over 2a, giving -3", "feedback": "The formula NEGATES b: minus (-6) over 2 is positive 3."},
   {"text": "x = -b over a, giving 6", "feedback": "The denominator is 2a, not a. Halve the 6."}
 ]'::jsonb,
 null),
('MPM2D', 'solving-quadratic-equations', 'standard-form-analysis', 2, 'Medium',
 'What is the vertex of y = x² - 6x + 2?', 2,
 '[
   {"text": "(3, 2)", "feedback": "The y of the vertex comes from SUBSTITUTING x = 3 into the whole equation, not from reading the constant."},
   {"text": "(-3, 29)", "feedback": "x = -b over 2a is minus (-6) over 2 — positive 3."},
   {"text": "(3, -7)", "feedback": "Correct."},
   {"text": "(6, 2)", "feedback": "The 2a in the denominator halves the 6."}
 ]'::jsonb,
 null),
('MPM2D', 'solving-quadratic-equations', 'standard-form-analysis', 3, 'Medium',
 'What is the axis of symmetry of y = 2x² + 8x - 1?', 0,
 '[
   {"text": "x = -2", "feedback": "Correct."},
   {"text": "x = -1", "feedback": "-1 is the y-intercept constant, nothing to do with the axis."},
   {"text": "x = 2", "feedback": "x = -b over 2a keeps the minus: -8 over 4."},
   {"text": "x = -4", "feedback": "The denominator is 2a = 4, not a = 2."}
 ]'::jsonb,
 null),
('MPM2D', 'solving-quadratic-equations', 'standard-form-analysis', 4, 'Challenge',
 'Profit follows P = -2x² + 120x - 1000. What price x gives the maximum profit?', 3,
 '[
   {"text": "-30", "feedback": "The two negatives cancel: -120 over -4 is positive."},
   {"text": "60", "feedback": "That divided by a instead of by 2a. Here 2a is -4, so the denominator is twice what was used."},
   {"text": "800", "feedback": "800 is the PROFIT at the best price, not the price itself."},
   {"text": "30", "feedback": "Correct."}
 ]'::jsonb,
 null),
('MPM2D', 'solving-quadratic-equations', 'standard-form-analysis', 5, 'Challenge',
 'For that profit model, what is the maximum profit?', 1,
 '[
   {"text": "1000", "feedback": "Substitute x = 30 through every term — the constant still subtracts at the end."},
   {"text": "800", "feedback": "Correct."},
   {"text": "2600", "feedback": "The -2x² term is negative at x = 30 — it pulls the total DOWN, not up."},
   {"text": "30", "feedback": "30 is the best PRICE. The profit is P evaluated there."}
 ]'::jsonb,
 null),
('MPM2D', 'solving-quadratic-equations', 'standard-form-analysis', 6, 'Advanced',
 'A rocket follows h = -4.9t² + 19.6t + 2. What is its maximum height?', 3,
 '[
   {"text": "19.6 m", "feedback": "19.6 is the launch speed coefficient. The peak needs t = 2 substituted through the whole formula."},
   {"text": "2 m", "feedback": "2 m is where it STARTED. The vertex is far above the launch pad."},
   {"text": "31.4 m", "feedback": "The first term at t = 2 is -4.9 times 4 — using -9.8, doubling instead of squaring, inflates the height."},
   {"text": "21.6 m", "feedback": "Correct."}
 ]'::jsonb,
 null);